export declare const Account: {
    name: string;
    label: string;
    pluralLabel: string;
    icon: string;
    description: string;
    nameField: string;
    fields: {
        account_number: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "autonumber";
        };
        name: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "text";
        };
        type: {
            readonly formula?: string | undefined;
            options: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[];
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "select";
        };
        industry: {
            readonly formula?: string | undefined;
            options: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[];
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "select";
        };
        annual_revenue: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "currency";
        };
        number_of_employees: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "number";
        };
        phone: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "text";
        };
        website: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "url";
        };
        billing_address: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "address";
        };
        office_location: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "location";
        };
        owner: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            reference: string;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "lookup";
        };
        parent_account: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            reference: string;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "lookup";
        };
        description: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "markdown";
        };
        is_active: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "boolean";
        };
        last_activity_date: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "date";
        };
        brand_color: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "color";
        };
    };
    indexes: {
        fields: string[];
        unique: false;
    }[];
    enable: {
        trackHistory: true;
        searchable: true;
        apiEnabled: true;
        apiMethods: ("get" | "list" | "create" | "update" | "delete" | "search" | "export")[];
        files: true;
        feedEnabled: true;
        trash: true;
    };
    list_views: {
        all: {
            label: string;
            type: string;
            columns: string[];
            sort: {
                field: string;
                order: string;
            }[];
            searchableFields: string[];
        };
        my_accounts: {
            label: string;
            type: string;
            columns: string[];
            filter: string[][];
            sort: {
                field: string;
                order: string;
            }[];
        };
        active_customers: {
            label: string;
            type: string;
            columns: string[];
            filter: (string | boolean)[][];
        };
        by_type: {
            label: string;
            type: string;
            columns: string[];
            kanban: {
                groupByField: string;
                summarizeField: string;
                columns: string[];
            };
        };
    };
    form_views: {
        default: {
            type: string;
            sections: ({
                label: string;
                columns: number;
                fields: string[];
                collapsible?: undefined;
                collapsed?: undefined;
            } | {
                label: string;
                columns: number;
                collapsible: boolean;
                collapsed: boolean;
                fields: string[];
            })[];
        };
    };
    validations: ({
        name: string;
        type: string;
        severity: string;
        message: string;
        condition: string;
        fields?: undefined;
        caseSensitive?: undefined;
    } | {
        name: string;
        type: string;
        severity: string;
        message: string;
        fields: string[];
        caseSensitive: boolean;
        condition?: undefined;
    })[];
    workflows: {
        name: string;
        objectName: string;
        triggerType: string;
        criteria: string;
        actions: {
            name: string;
            type: string;
            field: string;
            value: string;
        }[];
        active: boolean;
    }[];
};
//# sourceMappingURL=account.object.d.ts.map