export declare const Case: {
    name: string;
    label: string;
    pluralLabel: string;
    icon: string;
    description: string;
    fields: {
        case_number: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "autonumber";
        };
        subject: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "text";
        };
        description: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "markdown";
        };
        account: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            reference: string;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "lookup";
        };
        contact: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            reference: string;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "lookup";
        };
        status: {
            readonly formula?: string | undefined;
            options: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[];
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "select";
        };
        priority: {
            readonly formula?: string | undefined;
            options: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[];
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "select";
        };
        type: {
            readonly formula?: string | undefined;
            options: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[];
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "select";
        };
        origin: {
            readonly formula?: string | undefined;
            options: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[];
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "select";
        };
        owner: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            reference: string;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "lookup";
        };
        created_date: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "datetime";
        };
        closed_date: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "datetime";
        };
        first_response_date: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "datetime";
        };
        resolution_time_hours: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "number";
        };
        sla_due_date: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "datetime";
        };
        is_sla_violated: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "boolean";
        };
        is_escalated: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "boolean";
        };
        escalation_reason: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "textarea";
        };
        parent_case: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            reference: string;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "lookup";
        };
        resolution: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "markdown";
        };
        customer_rating: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            maxRating: number;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "rating";
        };
        customer_feedback: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "textarea";
        };
        customer_signature: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "signature";
        };
        internal_notes: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "markdown";
        };
        is_closed: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "boolean";
        };
    };
    indexes: ({
        fields: string[];
        unique: true;
    } | {
        fields: string[];
        unique: false;
    })[];
    enable: {
        trackHistory: true;
        searchable: true;
        apiEnabled: true;
        files: true;
        feedEnabled: true;
        trash: true;
    };
    nameField: string;
    list_views: {
        all: {
            label: string;
            type: string;
            columns: string[];
            sort: {
                field: string;
                order: string;
            }[];
            searchableFields: string[];
        };
        my_cases: {
            label: string;
            type: string;
            columns: string[];
            filter: string[][];
            sort: {
                field: string;
                order: string;
            }[];
        };
        open_cases: {
            label: string;
            type: string;
            columns: string[];
            filter: (string | boolean)[][];
            sort: {
                field: string;
                order: string;
            }[];
        };
        critical_cases: {
            label: string;
            type: string;
            columns: string[];
            filter: (string | boolean)[][];
            sort: {
                field: string;
                order: string;
            }[];
        };
        escalated_cases: {
            label: string;
            type: string;
            columns: string[];
            filter: (string | boolean)[][];
        };
        by_status: {
            label: string;
            type: string;
            columns: string[];
            filter: (string | boolean)[][];
            kanban: {
                groupByField: string;
                columns: string[];
            };
        };
        sla_violations: {
            label: string;
            type: string;
            columns: string[];
            filter: (string | boolean)[][];
            sort: {
                field: string;
                order: string;
            }[];
        };
    };
    form_views: {
        default: {
            type: string;
            sections: ({
                label: string;
                columns: number;
                fields: string[];
                collapsible?: undefined;
            } | {
                label: string;
                columns: number;
                collapsible: boolean;
                fields: string[];
            })[];
        };
    };
    validations: ({
        name: string;
        type: string;
        severity: string;
        message: string;
        condition: string;
        field?: undefined;
        transitions?: undefined;
    } | {
        name: string;
        type: string;
        severity: string;
        message: string;
        field: string;
        transitions: {
            new: string[];
            in_progress: string[];
            waiting_customer: string[];
            waiting_support: string[];
            escalated: string[];
            resolved: string[];
            closed: string[];
        };
        condition?: undefined;
    })[];
    workflows: ({
        name: string;
        objectName: string;
        triggerType: string;
        criteria: string;
        active: boolean;
        actions: {
            name: string;
            type: string;
            field: string;
            value: string;
        }[];
    } | {
        name: string;
        objectName: string;
        triggerType: string;
        criteria: string;
        active: boolean;
        actions: {
            name: string;
            type: string;
            template: string;
            recipients: string[];
        }[];
    })[];
};
//# sourceMappingURL=case.object.d.ts.map