export declare const Contact: {
    name: string;
    label: string;
    pluralLabel: string;
    icon: string;
    description: string;
    fields: {
        salutation: {
            readonly formula?: string | undefined;
            options: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[];
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "select";
        };
        first_name: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "text";
        };
        last_name: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "text";
        };
        full_name: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "formula";
        };
        account: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            reference: string;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "master_detail";
        };
        email: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "email";
        };
        phone: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "text";
        };
        mobile: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "text";
        };
        title: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "text";
        };
        department: {
            readonly formula?: string | undefined;
            options: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[];
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "select";
        };
        reports_to: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            reference: string;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "lookup";
        };
        owner: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            reference: string;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "lookup";
        };
        mailing_street: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "textarea";
        };
        mailing_city: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "text";
        };
        mailing_state: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "text";
        };
        mailing_postal_code: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "text";
        };
        mailing_country: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "text";
        };
        birthdate: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "date";
        };
        lead_source: {
            readonly formula?: string | undefined;
            options: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[];
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "select";
        };
        description: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "markdown";
        };
        is_primary: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "boolean";
        };
        do_not_call: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "boolean";
        };
        email_opt_out: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "boolean";
        };
        avatar: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "avatar";
        };
    };
    enable: {
        trackHistory: true;
        searchable: true;
        apiEnabled: true;
        files: true;
        feedEnabled: true;
        trash: true;
    };
    nameField: string;
    list_views: {
        all: {
            label: string;
            type: string;
            columns: string[];
            sort: {
                field: string;
                order: string;
            }[];
            searchableFields: string[];
        };
        my_contacts: {
            label: string;
            type: string;
            columns: string[];
            filter: string[][];
        };
        primary_contacts: {
            label: string;
            type: string;
            columns: string[];
            filter: (string | boolean)[][];
        };
        by_department: {
            label: string;
            type: string;
            columns: string[];
            kanban: {
                groupByField: string;
                columns: string[];
            };
        };
        birthdays: {
            label: string;
            type: string;
            columns: string[];
            calendar: {
                startDateField: string;
                titleField: string;
                colorField: string;
            };
        };
    };
    form_views: {
        default: {
            type: string;
            sections: ({
                label: string;
                columns: number;
                fields: string[];
                collapsible?: undefined;
            } | {
                label: string;
                columns: number;
                collapsible: boolean;
                fields: string[];
            })[];
        };
    };
    validations: ({
        name: string;
        type: string;
        severity: string;
        message: string;
        condition: string;
        fields?: undefined;
        caseSensitive?: undefined;
    } | {
        name: string;
        type: string;
        severity: string;
        message: string;
        fields: string[];
        caseSensitive: boolean;
        condition?: undefined;
    })[];
    workflows: {
        name: string;
        objectName: string;
        triggerType: string;
        active: boolean;
        actions: {
            name: string;
            type: string;
            template: string;
            recipients: string[];
        }[];
    }[];
};
//# sourceMappingURL=contact.object.d.ts.map