export declare const Opportunity: {
    name: string;
    label: string;
    pluralLabel: string;
    icon: string;
    description: string;
    nameField: string;
    fields: {
        name: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "text";
        };
        account: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            reference: string;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "lookup";
        };
        primary_contact: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            reference: string;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "lookup";
        };
        owner: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            reference: string;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "lookup";
        };
        amount: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "currency";
        };
        expected_revenue: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "currency";
        };
        stage: {
            readonly formula?: string | undefined;
            options: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[];
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "select";
        };
        probability: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "percent";
        };
        close_date: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "date";
        };
        created_date: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "datetime";
        };
        type: {
            readonly formula?: string | undefined;
            options: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[];
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "select";
        };
        lead_source: {
            readonly formula?: string | undefined;
            options: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[];
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "select";
        };
        competitors: {
            readonly formula?: string | undefined;
            options: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[];
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "select";
        };
        campaign: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            reference: string;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "lookup";
        };
        days_in_stage: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "number";
        };
        description: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "markdown";
        };
        next_step: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "textarea";
        };
        is_private: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "boolean";
        };
        forecast_category: {
            readonly formula?: string | undefined;
            options: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[];
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "select";
        };
    };
    indexes: {
        fields: string[];
        unique: false;
    }[];
    enable: {
        trackHistory: true;
        searchable: true;
        apiEnabled: true;
        apiMethods: ("get" | "list" | "create" | "update" | "delete" | "aggregate" | "search")[];
        files: true;
        feedEnabled: true;
        trash: true;
    };
    list_views: {
        all: {
            label: string;
            type: string;
            columns: string[];
            sort: {
                field: string;
                order: string;
            }[];
            searchableFields: string[];
        };
        my_opportunities: {
            label: string;
            type: string;
            columns: string[];
            filter: string[][];
            sort: {
                field: string;
                order: string;
            }[];
        };
        closing_this_month: {
            label: string;
            type: string;
            columns: string[];
            filter: string[][];
            sort: {
                field: string;
                order: string;
            }[];
        };
        won_opportunities: {
            label: string;
            type: string;
            columns: string[];
            filter: string[][];
            sort: {
                field: string;
                order: string;
            }[];
        };
        pipeline: {
            label: string;
            type: string;
            columns: string[];
            filter: string[][];
            kanban: {
                groupByField: string;
                summarizeField: string;
                columns: string[];
            };
        };
        timeline: {
            label: string;
            type: string;
            columns: string[];
            filter: string[][];
            gantt: {
                startDateField: string;
                endDateField: string;
                titleField: string;
                progressField: string;
            };
        };
    };
    form_views: {
        default: {
            type: string;
            sections: ({
                label: string;
                columns: number;
                fields: string[];
                collapsible?: undefined;
                collapsed?: undefined;
            } | {
                label: string;
                columns: number;
                collapsible: boolean;
                collapsed: boolean;
                fields: string[];
            })[];
        };
    };
    validations: ({
        name: string;
        type: string;
        severity: string;
        message: string;
        condition: string;
        field?: undefined;
        transitions?: undefined;
    } | {
        name: string;
        type: string;
        severity: string;
        message: string;
        field: string;
        transitions: {
            prospecting: string[];
            qualification: string[];
            needs_analysis: string[];
            proposal: string[];
            negotiation: string[];
            closed_won: never[];
            closed_lost: never[];
        };
        condition?: undefined;
    })[];
    workflows: ({
        name: string;
        objectName: string;
        triggerType: string;
        criteria: string;
        active: boolean;
        actions: {
            name: string;
            type: string;
            field: string;
            value: string;
        }[];
    } | {
        name: string;
        objectName: string;
        triggerType: string;
        criteria: string;
        active: boolean;
        actions: {
            name: string;
            type: string;
            template: string;
            recipients: string[];
        }[];
    })[];
};
//# sourceMappingURL=opportunity.object.d.ts.map