export declare const Task: {
    name: string;
    label: string;
    pluralLabel: string;
    icon: string;
    description: string;
    fields: {
        subject: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "text";
        };
        description: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "markdown";
        };
        status: {
            type: "select";
            label: string;
            required: true;
            options: ({
                label: string;
                value: string;
                color: string;
                default: true;
            } | {
                label: string;
                value: string;
                color: string;
                default?: undefined;
            })[];
        };
        priority: {
            type: "select";
            label: string;
            required: true;
            options: ({
                label: string;
                value: string;
                color: string;
                default: true;
            } | {
                label: string;
                value: string;
                color: string;
                default?: undefined;
            })[];
        };
        type: {
            readonly formula?: string | undefined;
            options: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[];
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "select";
        };
        due_date: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "date";
        };
        reminder_date: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "datetime";
        };
        completed_date: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "datetime";
        };
        owner: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            reference: string;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "lookup";
        };
        related_to_type: {
            readonly formula?: string | undefined;
            options: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[];
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "select";
        };
        related_to_account: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            reference: string;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "lookup";
        };
        related_to_contact: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            reference: string;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "lookup";
        };
        related_to_opportunity: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            reference: string;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "lookup";
        };
        related_to_lead: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            reference: string;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "lookup";
        };
        related_to_case: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            reference: string;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "lookup";
        };
        is_recurring: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "boolean";
        };
        recurrence_type: {
            readonly formula?: string | undefined;
            options: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[];
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "select";
        };
        recurrence_interval: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "number";
        };
        recurrence_end_date: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "date";
        };
        is_completed: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "boolean";
        };
        is_overdue: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "boolean";
        };
        progress_percent: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "percent";
        };
        estimated_hours: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "number";
        };
        actual_hours: {
            readonly formula?: string | undefined;
            readonly options?: {
                value: string;
                label: string;
                color?: string | undefined;
                default?: boolean | undefined;
            }[] | undefined;
            readonly label?: string | undefined;
            readonly name?: string | undefined;
            readonly description?: string | undefined;
            readonly format?: string | undefined;
            readonly required?: boolean | undefined;
            readonly searchable?: boolean | undefined;
            readonly multiple?: boolean | undefined;
            readonly unique?: boolean | undefined;
            readonly defaultValue?: any;
            readonly maxLength?: number | undefined;
            readonly minLength?: number | undefined;
            readonly precision?: number | undefined;
            readonly scale?: number | undefined;
            readonly min?: number | undefined;
            readonly max?: number | undefined;
            readonly reference?: string | undefined;
            readonly referenceFilters?: string[] | undefined;
            readonly writeRequiresMasterRead?: boolean | undefined;
            readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
            readonly expression?: string | undefined;
            readonly summaryOperations?: {
                object: string;
                function: "min" | "max" | "count" | "sum" | "avg";
                field: string;
            } | undefined;
            readonly language?: string | undefined;
            readonly theme?: string | undefined;
            readonly lineNumbers?: boolean | undefined;
            readonly maxRating?: number | undefined;
            readonly allowHalf?: boolean | undefined;
            readonly displayMap?: boolean | undefined;
            readonly allowGeocoding?: boolean | undefined;
            readonly addressFormat?: "us" | "uk" | "international" | undefined;
            readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
            readonly allowAlpha?: boolean | undefined;
            readonly presetColors?: string[] | undefined;
            readonly hidden?: boolean | undefined;
            readonly readonly?: boolean | undefined;
            readonly encryption?: boolean | undefined;
            readonly index?: boolean | undefined;
            readonly externalId?: boolean | undefined;
            readonly type: "number";
        };
    };
    enable: {
        trackHistory: true;
        searchable: true;
        apiEnabled: true;
        files: true;
        feedEnabled: true;
        trash: true;
    };
    nameField: string;
    list_views: {
        all: {
            label: string;
            type: string;
            columns: string[];
            sort: {
                field: string;
                order: string;
            }[];
            searchableFields: string[];
        };
        my_tasks: {
            label: string;
            type: string;
            columns: string[];
            filter: string[][];
            sort: {
                field: string;
                order: string;
            }[];
        };
        open_tasks: {
            label: string;
            type: string;
            columns: string[];
            filter: (string | boolean)[][];
            sort: {
                field: string;
                order: string;
            }[];
        };
        overdue_tasks: {
            label: string;
            type: string;
            columns: string[];
            filter: (string | boolean)[][];
            sort: {
                field: string;
                order: string;
            }[];
        };
        today_tasks: {
            label: string;
            type: string;
            columns: string[];
            filter: string[][];
        };
        by_status: {
            label: string;
            type: string;
            columns: string[];
            filter: (string | boolean)[][];
            kanban: {
                groupByField: string;
                columns: string[];
            };
        };
        calendar: {
            label: string;
            type: string;
            columns: string[];
            calendar: {
                startDateField: string;
                titleField: string;
                colorField: string;
            };
        };
    };
    form_views: {
        default: {
            type: string;
            sections: ({
                label: string;
                columns: number;
                fields: string[];
                collapsible?: undefined;
                collapsed?: undefined;
            } | {
                label: string;
                columns: number;
                collapsible: boolean;
                collapsed: boolean;
                fields: string[];
            })[];
        };
    };
    validations: {
        name: string;
        type: string;
        severity: string;
        message: string;
        condition: string;
    }[];
    workflows: ({
        name: string;
        objectName: string;
        triggerType: string;
        criteria: string;
        active: boolean;
        actions: {
            name: string;
            type: string;
            field: string;
            value: string;
        }[];
    } | {
        name: string;
        objectName: string;
        triggerType: string;
        criteria: string;
        active: boolean;
        actions: {
            name: string;
            type: string;
            template: string;
            recipients: string[];
        }[];
    })[];
};
//# sourceMappingURL=task.object.d.ts.map