// Define a simplified version of ObjectSchema to rely on, 
// avoiding direct dependency on @objectstack/spec to keep this package lightweight/portable if needed,
// or we can treat inputs as 'any' or generic structures that match the shape.
// For now, let's assume the input is the JSON structure compatible with what we saw in `object.zod.ts`.

export interface FieldDef {
  type: string;
  label?: string;
  required?: boolean;
  options?: string[];
  reference?: string;
}

export interface ObjectDef {
  name: string;
  fields: Record<string, FieldDef>;
  description?: string;
}

/**
 * Task 1: Static Type Generator
 */
export function generateTypeScriptDefinition(objects: ObjectDef[]): string {
  const interfaces = objects.map(obj => {
    const fields = Object.entries(obj.fields).map(([fieldName, field]) => {
      let tsType = 'any';
      
      switch (field.type) {
        case 'text':
        case 'textarea':
        case 'select':
        case 'email':
        case 'url':
        case 'phone':
            tsType = field.options ? field.options.map(o => `'${o}'`).join(' | ') : 'string';
            break;
        case 'number':
        case 'currency':
        case 'percent':
            tsType = 'number';
            break;
        case 'boolean':
            tsType = 'boolean';
            break;
        case 'date':
        case 'datetime':
            tsType = 'string'; // ISO string
            break;
        case 'lookup':
        case 'master_detail':
            tsType = field.reference ? `string | ${toPascalCase(field.reference)}` : 'string';
            break;
        case 'json':
            tsType = 'Record<string, any>';
            break;
        default:
            tsType = 'any';
      }

      const optionalMark = field.required ? '' : '?';
       // Doc comment for the field
       const doc = field.label ? `  /** ${field.label} */\n` : '';
      return `${doc}  ${fieldName}${optionalMark}: ${tsType};`;
    }).join('\n');

    const pascalName = toPascalCase(obj.name);
    
    // Generate Interface
    const interfaceDef = `/**
 * ${obj.description || obj.name}
 */
export interface ${pascalName} {
  _id: string;
${fields}
}`;

    // Generate ObjectQL Query Helper Types
    const queryTypeDef = `
export type ${pascalName}Filter = {
  [K in keyof ${pascalName}]?: ${pascalName}[K] | { 
    $eq?: ${pascalName}[K]; 
    $ne?: ${pascalName}[K]; 
    $gt?: any; 
    $lt?: any; 
    $in?: ${pascalName}[K][];
    $like?: string;
  };
};

export interface ${pascalName}Query {
  $select?: (keyof ${pascalName})[];
  $filter?: ${pascalName}Filter;
  $sort?: Partial<Record<keyof ${pascalName}, -1 | 1>>;
}
`;

    return interfaceDef + queryTypeDef;
  }).join('\n\n');

  return `// Auto-generated by ObjectStack AI Bridge
// Do not edit manually

${interfaces}
`;
}

function toPascalCase(str: string): string {
  return str.replace(/(^\w|_\w)/g, (m) => m.replace('_', '').toUpperCase());
}
