// Vercel Serverless Function — Catch-all API route.
//
// This file MUST be committed to the repository so Vercel can detect it
// as a serverless function during the pre-build phase.
//
// It delegates to the esbuild bundle (`_handler.js`) generated by
// `scripts/bundle-api.mjs` during the Vercel build step.  A separate
// bundle file is used (rather than overwriting this file) so that:
//   1. Vercel always finds this committed entry point (no "File not found").
//   2. Vercel does not TypeScript-compile a .ts stub that references
//      source files absent at runtime (no ERR_MODULE_NOT_FOUND).
//
// @see ../server/index.ts    — the actual server entrypoint
// @see ../scripts/bundle-api.mjs — the esbuild bundler

export { default, config } from './_handler.js';
