// Copyright (c) 2025 ObjectStack. Licensed under the Apache-2.0 license.

import { ObjectSchema, Field } from '@objectstack/spec/data';

/**
 * Auth User Object
 * 
 * Uses better-auth's native schema for seamless migration:
 * - id: string
 * - created_at: Date
 * - updated_at: Date
 * - email: string (unique, lowercase)
 * - email_verified: boolean
 * - name: string
 * - image: string | null
 */
export const AuthUser = ObjectSchema.create({
  name: 'user',
  label: 'User',
  pluralLabel: 'Users',
  icon: 'user',
  description: 'User accounts for authentication',
  titleFormat: '{name} ({email})',
  compactLayout: ['name', 'email', 'email_verified'],
  
  fields: {
    // ID is auto-generated by ObjectQL
    id: Field.text({
      label: 'User ID',
      required: true,
      readonly: true,
    }),
    
    created_at: Field.datetime({
      label: 'Created At',
      defaultValue: 'NOW()',
      readonly: true,
    }),
    
    updated_at: Field.datetime({
      label: 'Updated At',
      defaultValue: 'NOW()',
      readonly: true,
    }),
    
    email: Field.email({
      label: 'Email',
      required: true,
      searchable: true,
    }),
    
    email_verified: Field.boolean({
      label: 'Email Verified',
      defaultValue: false,
    }),
    
    name: Field.text({
      label: 'Name',
      required: true,
      searchable: true,
      maxLength: 255,
    }),
    
    image: Field.url({
      label: 'Profile Image',
      required: false,
    }),
  },
  
  // Database indexes for performance
  indexes: [
    { fields: ['email'], unique: true },
    { fields: ['created_at'], unique: false },
  ],
  
  // Enable features
  enable: {
    trackHistory: true,
    searchable: true,
    apiEnabled: true,
    apiMethods: ['get', 'list', 'create', 'update', 'delete'],
    trash: true,
    mru: true,
  },
  
  // Validation Rules
  validations: [
    {
      name: 'email_unique',
      type: 'unique',
      severity: 'error',
      message: 'Email must be unique',
      fields: ['email'],
      caseSensitive: false,
    },
  ],
});
