import type { Flow } from '@objectstack/spec/automation';

export const LeadConversionFlow: Flow = {
  name: 'lead_conversion',
  label: 'Lead Conversion Process',
  description: 'Automated flow to convert qualified leads to accounts, contacts, and opportunities',
  type: 'screen',
  triggerType: 'manual',
  objectName: 'lead',
  
  variables: [
    { name: 'leadId', type: 'text', required: true },
    { name: 'createOpportunity', type: 'boolean', defaultValue: true },
    { name: 'opportunityName', type: 'text' },
    { name: 'opportunityAmount', type: 'currency' },
  ],
  
  steps: [
    {
      id: 'screen_1',
      type: 'screen',
      label: 'Conversion Details',
      fields: [
        { name: 'createOpportunity', label: 'Create Opportunity?', type: 'boolean', required: true },
        { name: 'opportunityName', label: 'Opportunity Name', type: 'text', required: true, visibleWhen: '{createOpportunity} == true' },
        { name: 'opportunityAmount', label: 'Opportunity Amount', type: 'currency', visibleWhen: '{createOpportunity} == true' },
      ],
    },
    {
      id: 'get_lead',
      type: 'record_lookup',
      label: 'Get Lead Record',
      objectName: 'lead',
      filter: { id: '{leadId}' },
      outputVariable: 'leadRecord',
    },
    {
      id: 'create_account',
      type: 'record_create',
      label: 'Create Account',
      objectName: 'account',
      fields: {
        name: '{leadRecord.company}',
        phone: '{leadRecord.phone}',
        website: '{leadRecord.website}',
        industry: '{leadRecord.industry}',
        annual_revenue: '{leadRecord.annual_revenue}',
        number_of_employees: '{leadRecord.number_of_employees}',
        billing_address: '{leadRecord.address}',
        owner: '{$User.Id}',
        is_active: true,
      },
      outputVariable: 'accountId',
    },
    {
      id: 'create_contact',
      type: 'record_create',
      label: 'Create Contact',
      objectName: 'contact',
      fields: {
        first_name: '{leadRecord.first_name}',
        last_name: '{leadRecord.last_name}',
        email: '{leadRecord.email}',
        phone: '{leadRecord.phone}',
        title: '{leadRecord.title}',
        account: '{accountId}',
        is_primary: true,
        owner: '{$User.Id}',
      },
      outputVariable: 'contactId',
    },
    {
      id: 'decision_opportunity',
      type: 'decision',
      label: 'Create Opportunity?',
      condition: '{createOpportunity} == true',
      ifTrue: 'create_opportunity',
      ifFalse: 'mark_converted',
    },
    {
      id: 'create_opportunity',
      type: 'record_create',
      label: 'Create Opportunity',
      objectName: 'opportunity',
      fields: {
        name: '{opportunityName}',
        account: '{accountId}',
        contact: '{contactId}',
        amount: '{opportunityAmount}',
        stage: 'prospecting',
        probability: 10,
        lead_source: '{leadRecord.lead_source}',
        close_date: '{TODAY() + 90}',
        owner: '{$User.Id}',
      },
      outputVariable: 'opportunityId',
    },
    {
      id: 'mark_converted',
      type: 'record_update',
      label: 'Mark Lead as Converted',
      recordId: '{leadId}',
      objectName: 'lead',
      fields: {
        is_converted: true,
        converted_date: '{NOW()}',
        converted_account: '{accountId}',
        converted_contact: '{contactId}',
        converted_opportunity: '{opportunityId}',
      },
    },
    {
      id: 'send_notification',
      type: 'email_alert',
      label: 'Send Confirmation Email',
      template: 'lead_converted_notification',
      recipients: ['{$User.Email}'],
      variables: {
        leadName: '{leadRecord.full_name}',
        accountName: '{accountId.name}',
        contactName: '{contactId.full_name}',
      },
    },
  ],
};
