/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgsIndexRouteImport } from './routes/orgs.index'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as OrgsNewRouteImport } from './routes/orgs.new'
import { Route as OrgsOrgIdRouteImport } from './routes/orgs.$orgId'
import { Route as AuthDeviceRouteImport } from './routes/auth.device'
import { Route as AccountTwoFactorRouteImport } from './routes/account.two-factor'
import { Route as AccountSessionsRouteImport } from './routes/account.sessions'
import { Route as AccountSecurityRouteImport } from './routes/account.security'
import { Route as AccountProfileRouteImport } from './routes/account.profile'
import { Route as AcceptInvitationInvitationIdRouteImport } from './routes/accept-invitation.$invitationId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsIndexRoute = OrgsIndexRouteImport.update({
  id: '/orgs/',
  path: '/orgs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const OrgsNewRoute = OrgsNewRouteImport.update({
  id: '/orgs/new',
  path: '/orgs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsOrgIdRoute = OrgsOrgIdRouteImport.update({
  id: '/orgs/$orgId',
  path: '/orgs/$orgId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDeviceRoute = AuthDeviceRouteImport.update({
  id: '/auth/device',
  path: '/auth/device',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountTwoFactorRoute = AccountTwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => AccountRoute,
} as any)
const AccountSessionsRoute = AccountSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AccountRoute,
} as any)
const AccountSecurityRoute = AccountSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AccountRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRoute,
} as any)
const AcceptInvitationInvitationIdRoute =
  AcceptInvitationInvitationIdRouteImport.update({
    id: '/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/sessions': typeof AccountSessionsRoute
  '/account/two-factor': typeof AccountTwoFactorRoute
  '/auth/device': typeof AuthDeviceRoute
  '/orgs/$orgId': typeof OrgsOrgIdRoute
  '/orgs/new': typeof OrgsNewRoute
  '/account/': typeof AccountIndexRoute
  '/orgs/': typeof OrgsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/sessions': typeof AccountSessionsRoute
  '/account/two-factor': typeof AccountTwoFactorRoute
  '/auth/device': typeof AuthDeviceRoute
  '/orgs/$orgId': typeof OrgsOrgIdRoute
  '/orgs/new': typeof OrgsNewRoute
  '/account': typeof AccountIndexRoute
  '/orgs': typeof OrgsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/sessions': typeof AccountSessionsRoute
  '/account/two-factor': typeof AccountTwoFactorRoute
  '/auth/device': typeof AuthDeviceRoute
  '/orgs/$orgId': typeof OrgsOrgIdRoute
  '/orgs/new': typeof OrgsNewRoute
  '/account/': typeof AccountIndexRoute
  '/orgs/': typeof OrgsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/accept-invitation/$invitationId'
    | '/account/profile'
    | '/account/security'
    | '/account/sessions'
    | '/account/two-factor'
    | '/auth/device'
    | '/orgs/$orgId'
    | '/orgs/new'
    | '/account/'
    | '/orgs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/accept-invitation/$invitationId'
    | '/account/profile'
    | '/account/security'
    | '/account/sessions'
    | '/account/two-factor'
    | '/auth/device'
    | '/orgs/$orgId'
    | '/orgs/new'
    | '/account'
    | '/orgs'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/accept-invitation/$invitationId'
    | '/account/profile'
    | '/account/security'
    | '/account/sessions'
    | '/account/two-factor'
    | '/auth/device'
    | '/orgs/$orgId'
    | '/orgs/new'
    | '/account/'
    | '/orgs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AcceptInvitationInvitationIdRoute: typeof AcceptInvitationInvitationIdRoute
  AuthDeviceRoute: typeof AuthDeviceRoute
  OrgsOrgIdRoute: typeof OrgsOrgIdRoute
  OrgsNewRoute: typeof OrgsNewRoute
  OrgsIndexRoute: typeof OrgsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/': {
      id: '/orgs/'
      path: '/orgs'
      fullPath: '/orgs/'
      preLoaderRoute: typeof OrgsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/orgs/new': {
      id: '/orgs/new'
      path: '/orgs/new'
      fullPath: '/orgs/new'
      preLoaderRoute: typeof OrgsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/$orgId': {
      id: '/orgs/$orgId'
      path: '/orgs/$orgId'
      fullPath: '/orgs/$orgId'
      preLoaderRoute: typeof OrgsOrgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/device': {
      id: '/auth/device'
      path: '/auth/device'
      fullPath: '/auth/device'
      preLoaderRoute: typeof AuthDeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/two-factor': {
      id: '/account/two-factor'
      path: '/two-factor'
      fullPath: '/account/two-factor'
      preLoaderRoute: typeof AccountTwoFactorRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/sessions': {
      id: '/account/sessions'
      path: '/sessions'
      fullPath: '/account/sessions'
      preLoaderRoute: typeof AccountSessionsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/security': {
      id: '/account/security'
      path: '/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AccountSecurityRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRoute
    }
    '/accept-invitation/$invitationId': {
      id: '/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof AcceptInvitationInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountRouteChildren {
  AccountProfileRoute: typeof AccountProfileRoute
  AccountSecurityRoute: typeof AccountSecurityRoute
  AccountSessionsRoute: typeof AccountSessionsRoute
  AccountTwoFactorRoute: typeof AccountTwoFactorRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountProfileRoute: AccountProfileRoute,
  AccountSecurityRoute: AccountSecurityRoute,
  AccountSessionsRoute: AccountSessionsRoute,
  AccountTwoFactorRoute: AccountTwoFactorRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AcceptInvitationInvitationIdRoute: AcceptInvitationInvitationIdRoute,
  AuthDeviceRoute: AuthDeviceRoute,
  OrgsOrgIdRoute: OrgsOrgIdRoute,
  OrgsNewRoute: OrgsNewRoute,
  OrgsIndexRoute: OrgsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
