/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganizationsIndexRouteImport } from './routes/organizations.index'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as OrganizationsNewRouteImport } from './routes/organizations.new'
import { Route as OrganizationsOrgIdRouteImport } from './routes/organizations.$orgId'
import { Route as OauthConsentRouteImport } from './routes/oauth.consent'
import { Route as AuthDeviceRouteImport } from './routes/auth.device'
import { Route as AccountTwoFactorRouteImport } from './routes/account.two-factor'
import { Route as AccountSessionsRouteImport } from './routes/account.sessions'
import { Route as AccountSecurityRouteImport } from './routes/account.security'
import { Route as AccountProfileRouteImport } from './routes/account.profile'
import { Route as AccountLinkedAccountsRouteImport } from './routes/account.linked-accounts'
import { Route as AccountInvitationsRouteImport } from './routes/account.invitations'
import { Route as AcceptInvitationInvitationIdRouteImport } from './routes/accept-invitation.$invitationId'
import { Route as OrganizationsOrgIdIndexRouteImport } from './routes/organizations.$orgId.index'
import { Route as AccountOauthApplicationsIndexRouteImport } from './routes/account.oauth-applications.index'
import { Route as OrganizationsOrgIdTeamsRouteImport } from './routes/organizations.$orgId.teams'
import { Route as OrganizationsOrgIdMembersRouteImport } from './routes/organizations.$orgId.members'
import { Route as OrganizationsOrgIdGeneralRouteImport } from './routes/organizations.$orgId.general'
import { Route as AccountOauthApplicationsNewRouteImport } from './routes/account.oauth-applications.new'
import { Route as AccountOauthApplicationsClientIdRouteImport } from './routes/account.oauth-applications.$clientId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsIndexRoute = OrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const OrganizationsNewRoute = OrganizationsNewRouteImport.update({
  id: '/organizations/new',
  path: '/organizations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsOrgIdRoute = OrganizationsOrgIdRouteImport.update({
  id: '/organizations/$orgId',
  path: '/organizations/$orgId',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDeviceRoute = AuthDeviceRouteImport.update({
  id: '/auth/device',
  path: '/auth/device',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountTwoFactorRoute = AccountTwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => AccountRoute,
} as any)
const AccountSessionsRoute = AccountSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AccountRoute,
} as any)
const AccountSecurityRoute = AccountSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AccountRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRoute,
} as any)
const AccountLinkedAccountsRoute = AccountLinkedAccountsRouteImport.update({
  id: '/linked-accounts',
  path: '/linked-accounts',
  getParentRoute: () => AccountRoute,
} as any)
const AccountInvitationsRoute = AccountInvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => AccountRoute,
} as any)
const AcceptInvitationInvitationIdRoute =
  AcceptInvitationInvitationIdRouteImport.update({
    id: '/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizationsOrgIdIndexRoute = OrganizationsOrgIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrganizationsOrgIdRoute,
} as any)
const AccountOauthApplicationsIndexRoute =
  AccountOauthApplicationsIndexRouteImport.update({
    id: '/oauth-applications/',
    path: '/oauth-applications/',
    getParentRoute: () => AccountRoute,
  } as any)
const OrganizationsOrgIdTeamsRoute = OrganizationsOrgIdTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => OrganizationsOrgIdRoute,
} as any)
const OrganizationsOrgIdMembersRoute =
  OrganizationsOrgIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => OrganizationsOrgIdRoute,
  } as any)
const OrganizationsOrgIdGeneralRoute =
  OrganizationsOrgIdGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => OrganizationsOrgIdRoute,
  } as any)
const AccountOauthApplicationsNewRoute =
  AccountOauthApplicationsNewRouteImport.update({
    id: '/oauth-applications/new',
    path: '/oauth-applications/new',
    getParentRoute: () => AccountRoute,
  } as any)
const AccountOauthApplicationsClientIdRoute =
  AccountOauthApplicationsClientIdRouteImport.update({
    id: '/oauth-applications/$clientId',
    path: '/oauth-applications/$clientId',
    getParentRoute: () => AccountRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/account/invitations': typeof AccountInvitationsRoute
  '/account/linked-accounts': typeof AccountLinkedAccountsRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/sessions': typeof AccountSessionsRoute
  '/account/two-factor': typeof AccountTwoFactorRoute
  '/auth/device': typeof AuthDeviceRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/organizations/$orgId': typeof OrganizationsOrgIdRouteWithChildren
  '/organizations/new': typeof OrganizationsNewRoute
  '/account/': typeof AccountIndexRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/account/oauth-applications/$clientId': typeof AccountOauthApplicationsClientIdRoute
  '/account/oauth-applications/new': typeof AccountOauthApplicationsNewRoute
  '/organizations/$orgId/general': typeof OrganizationsOrgIdGeneralRoute
  '/organizations/$orgId/members': typeof OrganizationsOrgIdMembersRoute
  '/organizations/$orgId/teams': typeof OrganizationsOrgIdTeamsRoute
  '/account/oauth-applications/': typeof AccountOauthApplicationsIndexRoute
  '/organizations/$orgId/': typeof OrganizationsOrgIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/account/invitations': typeof AccountInvitationsRoute
  '/account/linked-accounts': typeof AccountLinkedAccountsRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/sessions': typeof AccountSessionsRoute
  '/account/two-factor': typeof AccountTwoFactorRoute
  '/auth/device': typeof AuthDeviceRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/organizations/new': typeof OrganizationsNewRoute
  '/account': typeof AccountIndexRoute
  '/organizations': typeof OrganizationsIndexRoute
  '/account/oauth-applications/$clientId': typeof AccountOauthApplicationsClientIdRoute
  '/account/oauth-applications/new': typeof AccountOauthApplicationsNewRoute
  '/organizations/$orgId/general': typeof OrganizationsOrgIdGeneralRoute
  '/organizations/$orgId/members': typeof OrganizationsOrgIdMembersRoute
  '/organizations/$orgId/teams': typeof OrganizationsOrgIdTeamsRoute
  '/account/oauth-applications': typeof AccountOauthApplicationsIndexRoute
  '/organizations/$orgId': typeof OrganizationsOrgIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/account/invitations': typeof AccountInvitationsRoute
  '/account/linked-accounts': typeof AccountLinkedAccountsRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/sessions': typeof AccountSessionsRoute
  '/account/two-factor': typeof AccountTwoFactorRoute
  '/auth/device': typeof AuthDeviceRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/organizations/$orgId': typeof OrganizationsOrgIdRouteWithChildren
  '/organizations/new': typeof OrganizationsNewRoute
  '/account/': typeof AccountIndexRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/account/oauth-applications/$clientId': typeof AccountOauthApplicationsClientIdRoute
  '/account/oauth-applications/new': typeof AccountOauthApplicationsNewRoute
  '/organizations/$orgId/general': typeof OrganizationsOrgIdGeneralRoute
  '/organizations/$orgId/members': typeof OrganizationsOrgIdMembersRoute
  '/organizations/$orgId/teams': typeof OrganizationsOrgIdTeamsRoute
  '/account/oauth-applications/': typeof AccountOauthApplicationsIndexRoute
  '/organizations/$orgId/': typeof OrganizationsOrgIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/setup'
    | '/verify-email'
    | '/accept-invitation/$invitationId'
    | '/account/invitations'
    | '/account/linked-accounts'
    | '/account/profile'
    | '/account/security'
    | '/account/sessions'
    | '/account/two-factor'
    | '/auth/device'
    | '/oauth/consent'
    | '/organizations/$orgId'
    | '/organizations/new'
    | '/account/'
    | '/organizations/'
    | '/account/oauth-applications/$clientId'
    | '/account/oauth-applications/new'
    | '/organizations/$orgId/general'
    | '/organizations/$orgId/members'
    | '/organizations/$orgId/teams'
    | '/account/oauth-applications/'
    | '/organizations/$orgId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/setup'
    | '/verify-email'
    | '/accept-invitation/$invitationId'
    | '/account/invitations'
    | '/account/linked-accounts'
    | '/account/profile'
    | '/account/security'
    | '/account/sessions'
    | '/account/two-factor'
    | '/auth/device'
    | '/oauth/consent'
    | '/organizations/new'
    | '/account'
    | '/organizations'
    | '/account/oauth-applications/$clientId'
    | '/account/oauth-applications/new'
    | '/organizations/$orgId/general'
    | '/organizations/$orgId/members'
    | '/organizations/$orgId/teams'
    | '/account/oauth-applications'
    | '/organizations/$orgId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/setup'
    | '/verify-email'
    | '/accept-invitation/$invitationId'
    | '/account/invitations'
    | '/account/linked-accounts'
    | '/account/profile'
    | '/account/security'
    | '/account/sessions'
    | '/account/two-factor'
    | '/auth/device'
    | '/oauth/consent'
    | '/organizations/$orgId'
    | '/organizations/new'
    | '/account/'
    | '/organizations/'
    | '/account/oauth-applications/$clientId'
    | '/account/oauth-applications/new'
    | '/organizations/$orgId/general'
    | '/organizations/$orgId/members'
    | '/organizations/$orgId/teams'
    | '/account/oauth-applications/'
    | '/organizations/$orgId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetupRoute: typeof SetupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AcceptInvitationInvitationIdRoute: typeof AcceptInvitationInvitationIdRoute
  AuthDeviceRoute: typeof AuthDeviceRoute
  OauthConsentRoute: typeof OauthConsentRoute
  OrganizationsOrgIdRoute: typeof OrganizationsOrgIdRouteWithChildren
  OrganizationsNewRoute: typeof OrganizationsNewRoute
  OrganizationsIndexRoute: typeof OrganizationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/': {
      id: '/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof OrganizationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/organizations/new': {
      id: '/organizations/new'
      path: '/organizations/new'
      fullPath: '/organizations/new'
      preLoaderRoute: typeof OrganizationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$orgId': {
      id: '/organizations/$orgId'
      path: '/organizations/$orgId'
      fullPath: '/organizations/$orgId'
      preLoaderRoute: typeof OrganizationsOrgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/device': {
      id: '/auth/device'
      path: '/auth/device'
      fullPath: '/auth/device'
      preLoaderRoute: typeof AuthDeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/two-factor': {
      id: '/account/two-factor'
      path: '/two-factor'
      fullPath: '/account/two-factor'
      preLoaderRoute: typeof AccountTwoFactorRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/sessions': {
      id: '/account/sessions'
      path: '/sessions'
      fullPath: '/account/sessions'
      preLoaderRoute: typeof AccountSessionsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/security': {
      id: '/account/security'
      path: '/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AccountSecurityRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/linked-accounts': {
      id: '/account/linked-accounts'
      path: '/linked-accounts'
      fullPath: '/account/linked-accounts'
      preLoaderRoute: typeof AccountLinkedAccountsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/invitations': {
      id: '/account/invitations'
      path: '/invitations'
      fullPath: '/account/invitations'
      preLoaderRoute: typeof AccountInvitationsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/accept-invitation/$invitationId': {
      id: '/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof AcceptInvitationInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$orgId/': {
      id: '/organizations/$orgId/'
      path: '/'
      fullPath: '/organizations/$orgId/'
      preLoaderRoute: typeof OrganizationsOrgIdIndexRouteImport
      parentRoute: typeof OrganizationsOrgIdRoute
    }
    '/account/oauth-applications/': {
      id: '/account/oauth-applications/'
      path: '/oauth-applications'
      fullPath: '/account/oauth-applications/'
      preLoaderRoute: typeof AccountOauthApplicationsIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/organizations/$orgId/teams': {
      id: '/organizations/$orgId/teams'
      path: '/teams'
      fullPath: '/organizations/$orgId/teams'
      preLoaderRoute: typeof OrganizationsOrgIdTeamsRouteImport
      parentRoute: typeof OrganizationsOrgIdRoute
    }
    '/organizations/$orgId/members': {
      id: '/organizations/$orgId/members'
      path: '/members'
      fullPath: '/organizations/$orgId/members'
      preLoaderRoute: typeof OrganizationsOrgIdMembersRouteImport
      parentRoute: typeof OrganizationsOrgIdRoute
    }
    '/organizations/$orgId/general': {
      id: '/organizations/$orgId/general'
      path: '/general'
      fullPath: '/organizations/$orgId/general'
      preLoaderRoute: typeof OrganizationsOrgIdGeneralRouteImport
      parentRoute: typeof OrganizationsOrgIdRoute
    }
    '/account/oauth-applications/new': {
      id: '/account/oauth-applications/new'
      path: '/oauth-applications/new'
      fullPath: '/account/oauth-applications/new'
      preLoaderRoute: typeof AccountOauthApplicationsNewRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/oauth-applications/$clientId': {
      id: '/account/oauth-applications/$clientId'
      path: '/oauth-applications/$clientId'
      fullPath: '/account/oauth-applications/$clientId'
      preLoaderRoute: typeof AccountOauthApplicationsClientIdRouteImport
      parentRoute: typeof AccountRoute
    }
  }
}

interface AccountRouteChildren {
  AccountInvitationsRoute: typeof AccountInvitationsRoute
  AccountLinkedAccountsRoute: typeof AccountLinkedAccountsRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountSecurityRoute: typeof AccountSecurityRoute
  AccountSessionsRoute: typeof AccountSessionsRoute
  AccountTwoFactorRoute: typeof AccountTwoFactorRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AccountOauthApplicationsClientIdRoute: typeof AccountOauthApplicationsClientIdRoute
  AccountOauthApplicationsNewRoute: typeof AccountOauthApplicationsNewRoute
  AccountOauthApplicationsIndexRoute: typeof AccountOauthApplicationsIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountInvitationsRoute: AccountInvitationsRoute,
  AccountLinkedAccountsRoute: AccountLinkedAccountsRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountSecurityRoute: AccountSecurityRoute,
  AccountSessionsRoute: AccountSessionsRoute,
  AccountTwoFactorRoute: AccountTwoFactorRoute,
  AccountIndexRoute: AccountIndexRoute,
  AccountOauthApplicationsClientIdRoute: AccountOauthApplicationsClientIdRoute,
  AccountOauthApplicationsNewRoute: AccountOauthApplicationsNewRoute,
  AccountOauthApplicationsIndexRoute: AccountOauthApplicationsIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface OrganizationsOrgIdRouteChildren {
  OrganizationsOrgIdGeneralRoute: typeof OrganizationsOrgIdGeneralRoute
  OrganizationsOrgIdMembersRoute: typeof OrganizationsOrgIdMembersRoute
  OrganizationsOrgIdTeamsRoute: typeof OrganizationsOrgIdTeamsRoute
  OrganizationsOrgIdIndexRoute: typeof OrganizationsOrgIdIndexRoute
}

const OrganizationsOrgIdRouteChildren: OrganizationsOrgIdRouteChildren = {
  OrganizationsOrgIdGeneralRoute: OrganizationsOrgIdGeneralRoute,
  OrganizationsOrgIdMembersRoute: OrganizationsOrgIdMembersRoute,
  OrganizationsOrgIdTeamsRoute: OrganizationsOrgIdTeamsRoute,
  OrganizationsOrgIdIndexRoute: OrganizationsOrgIdIndexRoute,
}

const OrganizationsOrgIdRouteWithChildren =
  OrganizationsOrgIdRoute._addFileChildren(OrganizationsOrgIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetupRoute: SetupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AcceptInvitationInvitationIdRoute: AcceptInvitationInvitationIdRoute,
  AuthDeviceRoute: AuthDeviceRoute,
  OauthConsentRoute: OauthConsentRoute,
  OrganizationsOrgIdRoute: OrganizationsOrgIdRouteWithChildren,
  OrganizationsNewRoute: OrganizationsNewRoute,
  OrganizationsIndexRoute: OrganizationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
