declare const _default: {
    name: string;
    label: string;
    description: string;
    version: string;
    icon: string;
    branding: {
        primaryColor: string;
        logo: string;
    };
    objects: {
        name: string;
        label: string;
        icon: string;
        nameField: string;
        enable: {
            apiEnabled: true;
            trackHistory: true;
        };
        fields: {
            subject: {
                readonly formula?: string | undefined;
                readonly options?: {
                    value: string;
                    label: string;
                    color?: string | undefined;
                    default?: boolean | undefined;
                }[] | undefined;
                readonly label?: string | undefined;
                readonly name?: string | undefined;
                readonly description?: string | undefined;
                readonly format?: string | undefined;
                readonly required?: boolean | undefined;
                readonly searchable?: boolean | undefined;
                readonly multiple?: boolean | undefined;
                readonly unique?: boolean | undefined;
                readonly defaultValue?: any;
                readonly maxLength?: number | undefined;
                readonly minLength?: number | undefined;
                readonly precision?: number | undefined;
                readonly scale?: number | undefined;
                readonly min?: number | undefined;
                readonly max?: number | undefined;
                readonly reference?: string | undefined;
                readonly referenceFilters?: string[] | undefined;
                readonly writeRequiresMasterRead?: boolean | undefined;
                readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
                readonly expression?: string | undefined;
                readonly summaryOperations?: {
                    object: string;
                    function: "min" | "max" | "count" | "sum" | "avg";
                    field: string;
                } | undefined;
                readonly language?: string | undefined;
                readonly theme?: string | undefined;
                readonly lineNumbers?: boolean | undefined;
                readonly maxRating?: number | undefined;
                readonly allowHalf?: boolean | undefined;
                readonly displayMap?: boolean | undefined;
                readonly allowGeocoding?: boolean | undefined;
                readonly addressFormat?: "us" | "uk" | "international" | undefined;
                readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
                readonly allowAlpha?: boolean | undefined;
                readonly presetColors?: string[] | undefined;
                readonly hidden?: boolean | undefined;
                readonly readonly?: boolean | undefined;
                readonly encryption?: boolean | undefined;
                readonly index?: boolean | undefined;
                readonly externalId?: boolean | undefined;
                readonly type: "text";
            };
            due_date: {
                readonly formula?: string | undefined;
                readonly options?: {
                    value: string;
                    label: string;
                    color?: string | undefined;
                    default?: boolean | undefined;
                }[] | undefined;
                readonly label?: string | undefined;
                readonly name?: string | undefined;
                readonly description?: string | undefined;
                readonly format?: string | undefined;
                readonly required?: boolean | undefined;
                readonly searchable?: boolean | undefined;
                readonly multiple?: boolean | undefined;
                readonly unique?: boolean | undefined;
                readonly defaultValue?: any;
                readonly maxLength?: number | undefined;
                readonly minLength?: number | undefined;
                readonly precision?: number | undefined;
                readonly scale?: number | undefined;
                readonly min?: number | undefined;
                readonly max?: number | undefined;
                readonly reference?: string | undefined;
                readonly referenceFilters?: string[] | undefined;
                readonly writeRequiresMasterRead?: boolean | undefined;
                readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
                readonly expression?: string | undefined;
                readonly summaryOperations?: {
                    object: string;
                    function: "min" | "max" | "count" | "sum" | "avg";
                    field: string;
                } | undefined;
                readonly language?: string | undefined;
                readonly theme?: string | undefined;
                readonly lineNumbers?: boolean | undefined;
                readonly maxRating?: number | undefined;
                readonly allowHalf?: boolean | undefined;
                readonly displayMap?: boolean | undefined;
                readonly allowGeocoding?: boolean | undefined;
                readonly addressFormat?: "us" | "uk" | "international" | undefined;
                readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
                readonly allowAlpha?: boolean | undefined;
                readonly presetColors?: string[] | undefined;
                readonly hidden?: boolean | undefined;
                readonly readonly?: boolean | undefined;
                readonly encryption?: boolean | undefined;
                readonly index?: boolean | undefined;
                readonly externalId?: boolean | undefined;
                readonly type: "date";
            };
            is_completed: {
                readonly formula?: string | undefined;
                readonly options?: {
                    value: string;
                    label: string;
                    color?: string | undefined;
                    default?: boolean | undefined;
                }[] | undefined;
                readonly label?: string | undefined;
                readonly name?: string | undefined;
                readonly description?: string | undefined;
                readonly format?: string | undefined;
                readonly required?: boolean | undefined;
                readonly searchable?: boolean | undefined;
                readonly multiple?: boolean | undefined;
                readonly unique?: boolean | undefined;
                readonly defaultValue?: any;
                readonly maxLength?: number | undefined;
                readonly minLength?: number | undefined;
                readonly precision?: number | undefined;
                readonly scale?: number | undefined;
                readonly min?: number | undefined;
                readonly max?: number | undefined;
                readonly reference?: string | undefined;
                readonly referenceFilters?: string[] | undefined;
                readonly writeRequiresMasterRead?: boolean | undefined;
                readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
                readonly expression?: string | undefined;
                readonly summaryOperations?: {
                    object: string;
                    function: "min" | "max" | "count" | "sum" | "avg";
                    field: string;
                } | undefined;
                readonly language?: string | undefined;
                readonly theme?: string | undefined;
                readonly lineNumbers?: boolean | undefined;
                readonly maxRating?: number | undefined;
                readonly allowHalf?: boolean | undefined;
                readonly displayMap?: boolean | undefined;
                readonly allowGeocoding?: boolean | undefined;
                readonly addressFormat?: "us" | "uk" | "international" | undefined;
                readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
                readonly allowAlpha?: boolean | undefined;
                readonly presetColors?: string[] | undefined;
                readonly hidden?: boolean | undefined;
                readonly readonly?: boolean | undefined;
                readonly encryption?: boolean | undefined;
                readonly index?: boolean | undefined;
                readonly externalId?: boolean | undefined;
                readonly type: "boolean";
            };
            priority: {
                readonly formula?: string | undefined;
                readonly options?: {
                    value: string;
                    label: string;
                    color?: string | undefined;
                    default?: boolean | undefined;
                }[] | undefined;
                readonly label?: string | undefined;
                readonly name?: string | undefined;
                readonly description?: string | undefined;
                readonly format?: string | undefined;
                readonly required?: boolean | undefined;
                readonly searchable?: boolean | undefined;
                readonly multiple?: boolean | undefined;
                readonly unique?: boolean | undefined;
                readonly defaultValue?: any;
                readonly maxLength?: number | undefined;
                readonly minLength?: number | undefined;
                readonly precision?: number | undefined;
                readonly scale?: number | undefined;
                readonly min?: number | undefined;
                readonly max?: number | undefined;
                readonly reference?: string | undefined;
                readonly referenceFilters?: string[] | undefined;
                readonly writeRequiresMasterRead?: boolean | undefined;
                readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
                readonly expression?: string | undefined;
                readonly summaryOperations?: {
                    object: string;
                    function: "min" | "max" | "count" | "sum" | "avg";
                    field: string;
                } | undefined;
                readonly language?: string | undefined;
                readonly theme?: string | undefined;
                readonly lineNumbers?: boolean | undefined;
                maxRating: number;
                readonly allowHalf?: boolean | undefined;
                readonly displayMap?: boolean | undefined;
                readonly allowGeocoding?: boolean | undefined;
                readonly addressFormat?: "us" | "uk" | "international" | undefined;
                readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
                readonly allowAlpha?: boolean | undefined;
                readonly presetColors?: string[] | undefined;
                readonly hidden?: boolean | undefined;
                readonly readonly?: boolean | undefined;
                readonly encryption?: boolean | undefined;
                readonly index?: boolean | undefined;
                readonly externalId?: boolean | undefined;
                readonly type: "rating";
            };
            category_color: {
                readonly formula?: string | undefined;
                readonly options?: {
                    value: string;
                    label: string;
                    color?: string | undefined;
                    default?: boolean | undefined;
                }[] | undefined;
                readonly label?: string | undefined;
                readonly name?: string | undefined;
                readonly description?: string | undefined;
                readonly format?: string | undefined;
                readonly required?: boolean | undefined;
                readonly searchable?: boolean | undefined;
                readonly multiple?: boolean | undefined;
                readonly unique?: boolean | undefined;
                readonly defaultValue?: any;
                readonly maxLength?: number | undefined;
                readonly minLength?: number | undefined;
                readonly precision?: number | undefined;
                readonly scale?: number | undefined;
                readonly min?: number | undefined;
                readonly max?: number | undefined;
                readonly reference?: string | undefined;
                readonly referenceFilters?: string[] | undefined;
                readonly writeRequiresMasterRead?: boolean | undefined;
                readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
                readonly expression?: string | undefined;
                readonly summaryOperations?: {
                    object: string;
                    function: "min" | "max" | "count" | "sum" | "avg";
                    field: string;
                } | undefined;
                readonly language?: string | undefined;
                readonly theme?: string | undefined;
                readonly lineNumbers?: boolean | undefined;
                readonly maxRating?: number | undefined;
                readonly allowHalf?: boolean | undefined;
                readonly displayMap?: boolean | undefined;
                readonly allowGeocoding?: boolean | undefined;
                readonly addressFormat?: "us" | "uk" | "international" | undefined;
                readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
                readonly allowAlpha?: boolean | undefined;
                readonly presetColors?: string[] | undefined;
                readonly hidden?: boolean | undefined;
                readonly readonly?: boolean | undefined;
                readonly encryption?: boolean | undefined;
                readonly index?: boolean | undefined;
                readonly externalId?: boolean | undefined;
                readonly type: "color";
            };
            code_snippet: {
                readonly formula?: string | undefined;
                readonly options?: {
                    value: string;
                    label: string;
                    color?: string | undefined;
                    default?: boolean | undefined;
                }[] | undefined;
                readonly label?: string | undefined;
                readonly name?: string | undefined;
                readonly description?: string | undefined;
                readonly format?: string | undefined;
                readonly required?: boolean | undefined;
                readonly searchable?: boolean | undefined;
                readonly multiple?: boolean | undefined;
                readonly unique?: boolean | undefined;
                readonly defaultValue?: any;
                readonly maxLength?: number | undefined;
                readonly minLength?: number | undefined;
                readonly precision?: number | undefined;
                readonly scale?: number | undefined;
                readonly min?: number | undefined;
                readonly max?: number | undefined;
                readonly reference?: string | undefined;
                readonly referenceFilters?: string[] | undefined;
                readonly writeRequiresMasterRead?: boolean | undefined;
                readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
                readonly expression?: string | undefined;
                readonly summaryOperations?: {
                    object: string;
                    function: "min" | "max" | "count" | "sum" | "avg";
                    field: string;
                } | undefined;
                language: string | undefined;
                readonly theme?: string | undefined;
                readonly lineNumbers?: boolean | undefined;
                readonly maxRating?: number | undefined;
                readonly allowHalf?: boolean | undefined;
                readonly displayMap?: boolean | undefined;
                readonly allowGeocoding?: boolean | undefined;
                readonly addressFormat?: "us" | "uk" | "international" | undefined;
                readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
                readonly allowAlpha?: boolean | undefined;
                readonly presetColors?: string[] | undefined;
                readonly hidden?: boolean | undefined;
                readonly readonly?: boolean | undefined;
                readonly encryption?: boolean | undefined;
                readonly index?: boolean | undefined;
                readonly externalId?: boolean | undefined;
                readonly type: "code";
            };
            notes: {
                readonly formula?: string | undefined;
                readonly options?: {
                    value: string;
                    label: string;
                    color?: string | undefined;
                    default?: boolean | undefined;
                }[] | undefined;
                readonly label?: string | undefined;
                readonly name?: string | undefined;
                readonly description?: string | undefined;
                readonly format?: string | undefined;
                readonly required?: boolean | undefined;
                readonly searchable?: boolean | undefined;
                readonly multiple?: boolean | undefined;
                readonly unique?: boolean | undefined;
                readonly defaultValue?: any;
                readonly maxLength?: number | undefined;
                readonly minLength?: number | undefined;
                readonly precision?: number | undefined;
                readonly scale?: number | undefined;
                readonly min?: number | undefined;
                readonly max?: number | undefined;
                readonly reference?: string | undefined;
                readonly referenceFilters?: string[] | undefined;
                readonly writeRequiresMasterRead?: boolean | undefined;
                readonly deleteBehavior?: "set_null" | "cascade" | "restrict" | undefined;
                readonly expression?: string | undefined;
                readonly summaryOperations?: {
                    object: string;
                    function: "min" | "max" | "count" | "sum" | "avg";
                    field: string;
                } | undefined;
                readonly language?: string | undefined;
                readonly theme?: string | undefined;
                readonly lineNumbers?: boolean | undefined;
                readonly maxRating?: number | undefined;
                readonly allowHalf?: boolean | undefined;
                readonly displayMap?: boolean | undefined;
                readonly allowGeocoding?: boolean | undefined;
                readonly addressFormat?: "us" | "uk" | "international" | undefined;
                readonly colorFormat?: "hex" | "rgb" | "rgba" | "hsl" | undefined;
                readonly allowAlpha?: boolean | undefined;
                readonly presetColors?: string[] | undefined;
                readonly hidden?: boolean | undefined;
                readonly readonly?: boolean | undefined;
                readonly encryption?: boolean | undefined;
                readonly index?: boolean | undefined;
                readonly externalId?: boolean | undefined;
                readonly type: "richtext";
            };
        };
    }[];
    navigation: {
        id: string;
        type: string;
        label: string;
        children: {
            id: string;
            type: string;
            objectName: string;
            label: string;
        }[];
    }[];
    data: {
        object: string;
        mode: string;
        records: ({
            subject: string;
            is_completed: boolean;
            priority: number;
            due_date: Date;
        } | {
            subject: string;
            is_completed: boolean;
            priority: number;
            due_date?: undefined;
        })[];
    }[];
};
export default _default;
//# sourceMappingURL=objectstack.config.d.ts.map