/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiConsoleRouteImport } from './routes/api-console'
import { Route as PackageRouteImport } from './routes/$package'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as OrgsIndexRouteImport } from './routes/orgs.index'
import { Route as PackageIndexRouteImport } from './routes/$package.index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as OrgsNewRouteImport } from './routes/orgs.new'
import { Route as OrgsOrgIdRouteImport } from './routes/orgs.$orgId'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects.$projectId.index'
import { Route as ProjectsProjectIdPackagesRouteImport } from './routes/projects.$projectId.packages'
import { Route as ProjectsProjectIdApiConsoleRouteImport } from './routes/projects.$projectId.api-console'
import { Route as ProjectsProjectIdPackageRouteImport } from './routes/projects.$projectId.$package'
import { Route as PackageObjectsNameRouteImport } from './routes/$package.objects.$name'
import { Route as ProjectsProjectIdPackageIndexRouteImport } from './routes/projects.$projectId.$package.index'
import { Route as PackageMetadataTypeNameRouteImport } from './routes/$package.metadata.$type.$name'
import { Route as ProjectsProjectIdPackageObjectsNameRouteImport } from './routes/projects.$projectId.$package.objects.$name'
import { Route as ProjectsProjectIdPackageMetadataTypeNameRouteImport } from './routes/projects.$projectId.$package.metadata.$type.$name'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConsoleRoute = ApiConsoleRouteImport.update({
  id: '/api-console',
  path: '/api-console',
  getParentRoute: () => rootRouteImport,
} as any)
const PackageRoute = PackageRouteImport.update({
  id: '/$package',
  path: '/$package',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsIndexRoute = OrgsIndexRouteImport.update({
  id: '/orgs/',
  path: '/orgs/',
  getParentRoute: () => rootRouteImport,
} as any)
const PackageIndexRoute = PackageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PackageRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsNewRoute = OrgsNewRouteImport.update({
  id: '/orgs/new',
  path: '/orgs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsOrgIdRoute = OrgsOrgIdRouteImport.update({
  id: '/orgs/$orgId',
  path: '/orgs/$orgId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdPackagesRoute =
  ProjectsProjectIdPackagesRouteImport.update({
    id: '/packages',
    path: '/packages',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdApiConsoleRoute =
  ProjectsProjectIdApiConsoleRouteImport.update({
    id: '/api-console',
    path: '/api-console',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdPackageRoute =
  ProjectsProjectIdPackageRouteImport.update({
    id: '/$package',
    path: '/$package',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const PackageObjectsNameRoute = PackageObjectsNameRouteImport.update({
  id: '/objects/$name',
  path: '/objects/$name',
  getParentRoute: () => PackageRoute,
} as any)
const ProjectsProjectIdPackageIndexRoute =
  ProjectsProjectIdPackageIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectsProjectIdPackageRoute,
  } as any)
const PackageMetadataTypeNameRoute = PackageMetadataTypeNameRouteImport.update({
  id: '/metadata/$type/$name',
  path: '/metadata/$type/$name',
  getParentRoute: () => PackageRoute,
} as any)
const ProjectsProjectIdPackageObjectsNameRoute =
  ProjectsProjectIdPackageObjectsNameRouteImport.update({
    id: '/objects/$name',
    path: '/objects/$name',
    getParentRoute: () => ProjectsProjectIdPackageRoute,
  } as any)
const ProjectsProjectIdPackageMetadataTypeNameRoute =
  ProjectsProjectIdPackageMetadataTypeNameRouteImport.update({
    id: '/metadata/$type/$name',
    path: '/metadata/$type/$name',
    getParentRoute: () => ProjectsProjectIdPackageRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$package': typeof PackageRouteWithChildren
  '/api-console': typeof ApiConsoleRoute
  '/login': typeof LoginRoute
  '/packages': typeof PackagesRoute
  '/register': typeof RegisterRoute
  '/orgs/$orgId': typeof OrgsOrgIdRoute
  '/orgs/new': typeof OrgsNewRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/$package/': typeof PackageIndexRoute
  '/orgs/': typeof OrgsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/$package/objects/$name': typeof PackageObjectsNameRoute
  '/projects/$projectId/$package': typeof ProjectsProjectIdPackageRouteWithChildren
  '/projects/$projectId/api-console': typeof ProjectsProjectIdApiConsoleRoute
  '/projects/$projectId/packages': typeof ProjectsProjectIdPackagesRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/$package/metadata/$type/$name': typeof PackageMetadataTypeNameRoute
  '/projects/$projectId/$package/': typeof ProjectsProjectIdPackageIndexRoute
  '/projects/$projectId/$package/objects/$name': typeof ProjectsProjectIdPackageObjectsNameRoute
  '/projects/$projectId/$package/metadata/$type/$name': typeof ProjectsProjectIdPackageMetadataTypeNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-console': typeof ApiConsoleRoute
  '/login': typeof LoginRoute
  '/packages': typeof PackagesRoute
  '/register': typeof RegisterRoute
  '/orgs/$orgId': typeof OrgsOrgIdRoute
  '/orgs/new': typeof OrgsNewRoute
  '/$package': typeof PackageIndexRoute
  '/orgs': typeof OrgsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/$package/objects/$name': typeof PackageObjectsNameRoute
  '/projects/$projectId/api-console': typeof ProjectsProjectIdApiConsoleRoute
  '/projects/$projectId/packages': typeof ProjectsProjectIdPackagesRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/$package/metadata/$type/$name': typeof PackageMetadataTypeNameRoute
  '/projects/$projectId/$package': typeof ProjectsProjectIdPackageIndexRoute
  '/projects/$projectId/$package/objects/$name': typeof ProjectsProjectIdPackageObjectsNameRoute
  '/projects/$projectId/$package/metadata/$type/$name': typeof ProjectsProjectIdPackageMetadataTypeNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$package': typeof PackageRouteWithChildren
  '/api-console': typeof ApiConsoleRoute
  '/login': typeof LoginRoute
  '/packages': typeof PackagesRoute
  '/register': typeof RegisterRoute
  '/orgs/$orgId': typeof OrgsOrgIdRoute
  '/orgs/new': typeof OrgsNewRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/$package/': typeof PackageIndexRoute
  '/orgs/': typeof OrgsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/$package/objects/$name': typeof PackageObjectsNameRoute
  '/projects/$projectId/$package': typeof ProjectsProjectIdPackageRouteWithChildren
  '/projects/$projectId/api-console': typeof ProjectsProjectIdApiConsoleRoute
  '/projects/$projectId/packages': typeof ProjectsProjectIdPackagesRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/$package/metadata/$type/$name': typeof PackageMetadataTypeNameRoute
  '/projects/$projectId/$package/': typeof ProjectsProjectIdPackageIndexRoute
  '/projects/$projectId/$package/objects/$name': typeof ProjectsProjectIdPackageObjectsNameRoute
  '/projects/$projectId/$package/metadata/$type/$name': typeof ProjectsProjectIdPackageMetadataTypeNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$package'
    | '/api-console'
    | '/login'
    | '/packages'
    | '/register'
    | '/orgs/$orgId'
    | '/orgs/new'
    | '/projects/$projectId'
    | '/$package/'
    | '/orgs/'
    | '/projects/'
    | '/$package/objects/$name'
    | '/projects/$projectId/$package'
    | '/projects/$projectId/api-console'
    | '/projects/$projectId/packages'
    | '/projects/$projectId/'
    | '/$package/metadata/$type/$name'
    | '/projects/$projectId/$package/'
    | '/projects/$projectId/$package/objects/$name'
    | '/projects/$projectId/$package/metadata/$type/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-console'
    | '/login'
    | '/packages'
    | '/register'
    | '/orgs/$orgId'
    | '/orgs/new'
    | '/$package'
    | '/orgs'
    | '/projects'
    | '/$package/objects/$name'
    | '/projects/$projectId/api-console'
    | '/projects/$projectId/packages'
    | '/projects/$projectId'
    | '/$package/metadata/$type/$name'
    | '/projects/$projectId/$package'
    | '/projects/$projectId/$package/objects/$name'
    | '/projects/$projectId/$package/metadata/$type/$name'
  id:
    | '__root__'
    | '/'
    | '/$package'
    | '/api-console'
    | '/login'
    | '/packages'
    | '/register'
    | '/orgs/$orgId'
    | '/orgs/new'
    | '/projects/$projectId'
    | '/$package/'
    | '/orgs/'
    | '/projects/'
    | '/$package/objects/$name'
    | '/projects/$projectId/$package'
    | '/projects/$projectId/api-console'
    | '/projects/$projectId/packages'
    | '/projects/$projectId/'
    | '/$package/metadata/$type/$name'
    | '/projects/$projectId/$package/'
    | '/projects/$projectId/$package/objects/$name'
    | '/projects/$projectId/$package/metadata/$type/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PackageRoute: typeof PackageRouteWithChildren
  ApiConsoleRoute: typeof ApiConsoleRoute
  LoginRoute: typeof LoginRoute
  PackagesRoute: typeof PackagesRoute
  RegisterRoute: typeof RegisterRoute
  OrgsOrgIdRoute: typeof OrgsOrgIdRoute
  OrgsNewRoute: typeof OrgsNewRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  OrgsIndexRoute: typeof OrgsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-console': {
      id: '/api-console'
      path: '/api-console'
      fullPath: '/api-console'
      preLoaderRoute: typeof ApiConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$package': {
      id: '/$package'
      path: '/$package'
      fullPath: '/$package'
      preLoaderRoute: typeof PackageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/': {
      id: '/orgs/'
      path: '/orgs'
      fullPath: '/orgs/'
      preLoaderRoute: typeof OrgsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$package/': {
      id: '/$package/'
      path: '/'
      fullPath: '/$package/'
      preLoaderRoute: typeof PackageIndexRouteImport
      parentRoute: typeof PackageRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/new': {
      id: '/orgs/new'
      path: '/orgs/new'
      fullPath: '/orgs/new'
      preLoaderRoute: typeof OrgsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/$orgId': {
      id: '/orgs/$orgId'
      path: '/orgs/$orgId'
      fullPath: '/orgs/$orgId'
      preLoaderRoute: typeof OrgsOrgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/packages': {
      id: '/projects/$projectId/packages'
      path: '/packages'
      fullPath: '/projects/$projectId/packages'
      preLoaderRoute: typeof ProjectsProjectIdPackagesRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/api-console': {
      id: '/projects/$projectId/api-console'
      path: '/api-console'
      fullPath: '/projects/$projectId/api-console'
      preLoaderRoute: typeof ProjectsProjectIdApiConsoleRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/$package': {
      id: '/projects/$projectId/$package'
      path: '/$package'
      fullPath: '/projects/$projectId/$package'
      preLoaderRoute: typeof ProjectsProjectIdPackageRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/$package/objects/$name': {
      id: '/$package/objects/$name'
      path: '/objects/$name'
      fullPath: '/$package/objects/$name'
      preLoaderRoute: typeof PackageObjectsNameRouteImport
      parentRoute: typeof PackageRoute
    }
    '/projects/$projectId/$package/': {
      id: '/projects/$projectId/$package/'
      path: '/'
      fullPath: '/projects/$projectId/$package/'
      preLoaderRoute: typeof ProjectsProjectIdPackageIndexRouteImport
      parentRoute: typeof ProjectsProjectIdPackageRoute
    }
    '/$package/metadata/$type/$name': {
      id: '/$package/metadata/$type/$name'
      path: '/metadata/$type/$name'
      fullPath: '/$package/metadata/$type/$name'
      preLoaderRoute: typeof PackageMetadataTypeNameRouteImport
      parentRoute: typeof PackageRoute
    }
    '/projects/$projectId/$package/objects/$name': {
      id: '/projects/$projectId/$package/objects/$name'
      path: '/objects/$name'
      fullPath: '/projects/$projectId/$package/objects/$name'
      preLoaderRoute: typeof ProjectsProjectIdPackageObjectsNameRouteImport
      parentRoute: typeof ProjectsProjectIdPackageRoute
    }
    '/projects/$projectId/$package/metadata/$type/$name': {
      id: '/projects/$projectId/$package/metadata/$type/$name'
      path: '/metadata/$type/$name'
      fullPath: '/projects/$projectId/$package/metadata/$type/$name'
      preLoaderRoute: typeof ProjectsProjectIdPackageMetadataTypeNameRouteImport
      parentRoute: typeof ProjectsProjectIdPackageRoute
    }
  }
}

interface PackageRouteChildren {
  PackageIndexRoute: typeof PackageIndexRoute
  PackageObjectsNameRoute: typeof PackageObjectsNameRoute
  PackageMetadataTypeNameRoute: typeof PackageMetadataTypeNameRoute
}

const PackageRouteChildren: PackageRouteChildren = {
  PackageIndexRoute: PackageIndexRoute,
  PackageObjectsNameRoute: PackageObjectsNameRoute,
  PackageMetadataTypeNameRoute: PackageMetadataTypeNameRoute,
}

const PackageRouteWithChildren =
  PackageRoute._addFileChildren(PackageRouteChildren)

interface ProjectsProjectIdPackageRouteChildren {
  ProjectsProjectIdPackageIndexRoute: typeof ProjectsProjectIdPackageIndexRoute
  ProjectsProjectIdPackageObjectsNameRoute: typeof ProjectsProjectIdPackageObjectsNameRoute
  ProjectsProjectIdPackageMetadataTypeNameRoute: typeof ProjectsProjectIdPackageMetadataTypeNameRoute
}

const ProjectsProjectIdPackageRouteChildren: ProjectsProjectIdPackageRouteChildren =
  {
    ProjectsProjectIdPackageIndexRoute: ProjectsProjectIdPackageIndexRoute,
    ProjectsProjectIdPackageObjectsNameRoute:
      ProjectsProjectIdPackageObjectsNameRoute,
    ProjectsProjectIdPackageMetadataTypeNameRoute:
      ProjectsProjectIdPackageMetadataTypeNameRoute,
  }

const ProjectsProjectIdPackageRouteWithChildren =
  ProjectsProjectIdPackageRoute._addFileChildren(
    ProjectsProjectIdPackageRouteChildren,
  )

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdPackageRoute: typeof ProjectsProjectIdPackageRouteWithChildren
  ProjectsProjectIdApiConsoleRoute: typeof ProjectsProjectIdApiConsoleRoute
  ProjectsProjectIdPackagesRoute: typeof ProjectsProjectIdPackagesRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdPackageRoute: ProjectsProjectIdPackageRouteWithChildren,
  ProjectsProjectIdApiConsoleRoute: ProjectsProjectIdApiConsoleRoute,
  ProjectsProjectIdPackagesRoute: ProjectsProjectIdPackagesRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PackageRoute: PackageRouteWithChildren,
  ApiConsoleRoute: ApiConsoleRoute,
  LoginRoute: LoginRoute,
  PackagesRoute: PackagesRoute,
  RegisterRoute: RegisterRoute,
  OrgsOrgIdRoute: OrgsOrgIdRoute,
  OrgsNewRoute: OrgsNewRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  OrgsIndexRoute: OrgsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
