/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiConsoleRouteImport } from './routes/api-console'
import { Route as PackageRouteImport } from './routes/$package'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgsIndexRouteImport } from './routes/orgs.index'
import { Route as EnvironmentsIndexRouteImport } from './routes/environments.index'
import { Route as PackageIndexRouteImport } from './routes/$package.index'
import { Route as OrgsNewRouteImport } from './routes/orgs.new'
import { Route as OrgsOrgIdRouteImport } from './routes/orgs.$orgId'
import { Route as EnvironmentsEnvironmentIdRouteImport } from './routes/environments.$environmentId'
import { Route as EnvironmentsEnvironmentIdIndexRouteImport } from './routes/environments.$environmentId.index'
import { Route as EnvironmentsEnvironmentIdPackagesRouteImport } from './routes/environments.$environmentId.packages'
import { Route as EnvironmentsEnvironmentIdPackageRouteImport } from './routes/environments.$environmentId.$package'
import { Route as PackageObjectsNameRouteImport } from './routes/$package.objects.$name'
import { Route as EnvironmentsEnvironmentIdPackageIndexRouteImport } from './routes/environments.$environmentId.$package.index'
import { Route as PackageMetadataTypeNameRouteImport } from './routes/$package.metadata.$type.$name'
import { Route as EnvironmentsEnvironmentIdPackageObjectsNameRouteImport } from './routes/environments.$environmentId.$package.objects.$name'
import { Route as EnvironmentsEnvironmentIdPackageMetadataTypeNameRouteImport } from './routes/environments.$environmentId.$package.metadata.$type.$name'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConsoleRoute = ApiConsoleRouteImport.update({
  id: '/api-console',
  path: '/api-console',
  getParentRoute: () => rootRouteImport,
} as any)
const PackageRoute = PackageRouteImport.update({
  id: '/$package',
  path: '/$package',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsIndexRoute = OrgsIndexRouteImport.update({
  id: '/orgs/',
  path: '/orgs/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvironmentsIndexRoute = EnvironmentsIndexRouteImport.update({
  id: '/environments/',
  path: '/environments/',
  getParentRoute: () => rootRouteImport,
} as any)
const PackageIndexRoute = PackageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PackageRoute,
} as any)
const OrgsNewRoute = OrgsNewRouteImport.update({
  id: '/orgs/new',
  path: '/orgs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsOrgIdRoute = OrgsOrgIdRouteImport.update({
  id: '/orgs/$orgId',
  path: '/orgs/$orgId',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvironmentsEnvironmentIdRoute =
  EnvironmentsEnvironmentIdRouteImport.update({
    id: '/environments/$environmentId',
    path: '/environments/$environmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const EnvironmentsEnvironmentIdIndexRoute =
  EnvironmentsEnvironmentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => EnvironmentsEnvironmentIdRoute,
  } as any)
const EnvironmentsEnvironmentIdPackagesRoute =
  EnvironmentsEnvironmentIdPackagesRouteImport.update({
    id: '/packages',
    path: '/packages',
    getParentRoute: () => EnvironmentsEnvironmentIdRoute,
  } as any)
const EnvironmentsEnvironmentIdPackageRoute =
  EnvironmentsEnvironmentIdPackageRouteImport.update({
    id: '/$package',
    path: '/$package',
    getParentRoute: () => EnvironmentsEnvironmentIdRoute,
  } as any)
const PackageObjectsNameRoute = PackageObjectsNameRouteImport.update({
  id: '/objects/$name',
  path: '/objects/$name',
  getParentRoute: () => PackageRoute,
} as any)
const EnvironmentsEnvironmentIdPackageIndexRoute =
  EnvironmentsEnvironmentIdPackageIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => EnvironmentsEnvironmentIdPackageRoute,
  } as any)
const PackageMetadataTypeNameRoute = PackageMetadataTypeNameRouteImport.update({
  id: '/metadata/$type/$name',
  path: '/metadata/$type/$name',
  getParentRoute: () => PackageRoute,
} as any)
const EnvironmentsEnvironmentIdPackageObjectsNameRoute =
  EnvironmentsEnvironmentIdPackageObjectsNameRouteImport.update({
    id: '/objects/$name',
    path: '/objects/$name',
    getParentRoute: () => EnvironmentsEnvironmentIdPackageRoute,
  } as any)
const EnvironmentsEnvironmentIdPackageMetadataTypeNameRoute =
  EnvironmentsEnvironmentIdPackageMetadataTypeNameRouteImport.update({
    id: '/metadata/$type/$name',
    path: '/metadata/$type/$name',
    getParentRoute: () => EnvironmentsEnvironmentIdPackageRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$package': typeof PackageRouteWithChildren
  '/api-console': typeof ApiConsoleRoute
  '/login': typeof LoginRoute
  '/packages': typeof PackagesRoute
  '/register': typeof RegisterRoute
  '/environments/$environmentId': typeof EnvironmentsEnvironmentIdRouteWithChildren
  '/orgs/$orgId': typeof OrgsOrgIdRoute
  '/orgs/new': typeof OrgsNewRoute
  '/$package/': typeof PackageIndexRoute
  '/environments/': typeof EnvironmentsIndexRoute
  '/orgs/': typeof OrgsIndexRoute
  '/$package/objects/$name': typeof PackageObjectsNameRoute
  '/environments/$environmentId/$package': typeof EnvironmentsEnvironmentIdPackageRouteWithChildren
  '/environments/$environmentId/packages': typeof EnvironmentsEnvironmentIdPackagesRoute
  '/environments/$environmentId/': typeof EnvironmentsEnvironmentIdIndexRoute
  '/$package/metadata/$type/$name': typeof PackageMetadataTypeNameRoute
  '/environments/$environmentId/$package/': typeof EnvironmentsEnvironmentIdPackageIndexRoute
  '/environments/$environmentId/$package/objects/$name': typeof EnvironmentsEnvironmentIdPackageObjectsNameRoute
  '/environments/$environmentId/$package/metadata/$type/$name': typeof EnvironmentsEnvironmentIdPackageMetadataTypeNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-console': typeof ApiConsoleRoute
  '/login': typeof LoginRoute
  '/packages': typeof PackagesRoute
  '/register': typeof RegisterRoute
  '/orgs/$orgId': typeof OrgsOrgIdRoute
  '/orgs/new': typeof OrgsNewRoute
  '/$package': typeof PackageIndexRoute
  '/environments': typeof EnvironmentsIndexRoute
  '/orgs': typeof OrgsIndexRoute
  '/$package/objects/$name': typeof PackageObjectsNameRoute
  '/environments/$environmentId/packages': typeof EnvironmentsEnvironmentIdPackagesRoute
  '/environments/$environmentId': typeof EnvironmentsEnvironmentIdIndexRoute
  '/$package/metadata/$type/$name': typeof PackageMetadataTypeNameRoute
  '/environments/$environmentId/$package': typeof EnvironmentsEnvironmentIdPackageIndexRoute
  '/environments/$environmentId/$package/objects/$name': typeof EnvironmentsEnvironmentIdPackageObjectsNameRoute
  '/environments/$environmentId/$package/metadata/$type/$name': typeof EnvironmentsEnvironmentIdPackageMetadataTypeNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$package': typeof PackageRouteWithChildren
  '/api-console': typeof ApiConsoleRoute
  '/login': typeof LoginRoute
  '/packages': typeof PackagesRoute
  '/register': typeof RegisterRoute
  '/environments/$environmentId': typeof EnvironmentsEnvironmentIdRouteWithChildren
  '/orgs/$orgId': typeof OrgsOrgIdRoute
  '/orgs/new': typeof OrgsNewRoute
  '/$package/': typeof PackageIndexRoute
  '/environments/': typeof EnvironmentsIndexRoute
  '/orgs/': typeof OrgsIndexRoute
  '/$package/objects/$name': typeof PackageObjectsNameRoute
  '/environments/$environmentId/$package': typeof EnvironmentsEnvironmentIdPackageRouteWithChildren
  '/environments/$environmentId/packages': typeof EnvironmentsEnvironmentIdPackagesRoute
  '/environments/$environmentId/': typeof EnvironmentsEnvironmentIdIndexRoute
  '/$package/metadata/$type/$name': typeof PackageMetadataTypeNameRoute
  '/environments/$environmentId/$package/': typeof EnvironmentsEnvironmentIdPackageIndexRoute
  '/environments/$environmentId/$package/objects/$name': typeof EnvironmentsEnvironmentIdPackageObjectsNameRoute
  '/environments/$environmentId/$package/metadata/$type/$name': typeof EnvironmentsEnvironmentIdPackageMetadataTypeNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$package'
    | '/api-console'
    | '/login'
    | '/packages'
    | '/register'
    | '/environments/$environmentId'
    | '/orgs/$orgId'
    | '/orgs/new'
    | '/$package/'
    | '/environments/'
    | '/orgs/'
    | '/$package/objects/$name'
    | '/environments/$environmentId/$package'
    | '/environments/$environmentId/packages'
    | '/environments/$environmentId/'
    | '/$package/metadata/$type/$name'
    | '/environments/$environmentId/$package/'
    | '/environments/$environmentId/$package/objects/$name'
    | '/environments/$environmentId/$package/metadata/$type/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-console'
    | '/login'
    | '/packages'
    | '/register'
    | '/orgs/$orgId'
    | '/orgs/new'
    | '/$package'
    | '/environments'
    | '/orgs'
    | '/$package/objects/$name'
    | '/environments/$environmentId/packages'
    | '/environments/$environmentId'
    | '/$package/metadata/$type/$name'
    | '/environments/$environmentId/$package'
    | '/environments/$environmentId/$package/objects/$name'
    | '/environments/$environmentId/$package/metadata/$type/$name'
  id:
    | '__root__'
    | '/'
    | '/$package'
    | '/api-console'
    | '/login'
    | '/packages'
    | '/register'
    | '/environments/$environmentId'
    | '/orgs/$orgId'
    | '/orgs/new'
    | '/$package/'
    | '/environments/'
    | '/orgs/'
    | '/$package/objects/$name'
    | '/environments/$environmentId/$package'
    | '/environments/$environmentId/packages'
    | '/environments/$environmentId/'
    | '/$package/metadata/$type/$name'
    | '/environments/$environmentId/$package/'
    | '/environments/$environmentId/$package/objects/$name'
    | '/environments/$environmentId/$package/metadata/$type/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PackageRoute: typeof PackageRouteWithChildren
  ApiConsoleRoute: typeof ApiConsoleRoute
  LoginRoute: typeof LoginRoute
  PackagesRoute: typeof PackagesRoute
  RegisterRoute: typeof RegisterRoute
  EnvironmentsEnvironmentIdRoute: typeof EnvironmentsEnvironmentIdRouteWithChildren
  OrgsOrgIdRoute: typeof OrgsOrgIdRoute
  OrgsNewRoute: typeof OrgsNewRoute
  EnvironmentsIndexRoute: typeof EnvironmentsIndexRoute
  OrgsIndexRoute: typeof OrgsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-console': {
      id: '/api-console'
      path: '/api-console'
      fullPath: '/api-console'
      preLoaderRoute: typeof ApiConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$package': {
      id: '/$package'
      path: '/$package'
      fullPath: '/$package'
      preLoaderRoute: typeof PackageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/': {
      id: '/orgs/'
      path: '/orgs'
      fullPath: '/orgs/'
      preLoaderRoute: typeof OrgsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/environments/': {
      id: '/environments/'
      path: '/environments'
      fullPath: '/environments/'
      preLoaderRoute: typeof EnvironmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$package/': {
      id: '/$package/'
      path: '/'
      fullPath: '/$package/'
      preLoaderRoute: typeof PackageIndexRouteImport
      parentRoute: typeof PackageRoute
    }
    '/orgs/new': {
      id: '/orgs/new'
      path: '/orgs/new'
      fullPath: '/orgs/new'
      preLoaderRoute: typeof OrgsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/$orgId': {
      id: '/orgs/$orgId'
      path: '/orgs/$orgId'
      fullPath: '/orgs/$orgId'
      preLoaderRoute: typeof OrgsOrgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/environments/$environmentId': {
      id: '/environments/$environmentId'
      path: '/environments/$environmentId'
      fullPath: '/environments/$environmentId'
      preLoaderRoute: typeof EnvironmentsEnvironmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/environments/$environmentId/': {
      id: '/environments/$environmentId/'
      path: '/'
      fullPath: '/environments/$environmentId/'
      preLoaderRoute: typeof EnvironmentsEnvironmentIdIndexRouteImport
      parentRoute: typeof EnvironmentsEnvironmentIdRoute
    }
    '/environments/$environmentId/packages': {
      id: '/environments/$environmentId/packages'
      path: '/packages'
      fullPath: '/environments/$environmentId/packages'
      preLoaderRoute: typeof EnvironmentsEnvironmentIdPackagesRouteImport
      parentRoute: typeof EnvironmentsEnvironmentIdRoute
    }
    '/environments/$environmentId/$package': {
      id: '/environments/$environmentId/$package'
      path: '/$package'
      fullPath: '/environments/$environmentId/$package'
      preLoaderRoute: typeof EnvironmentsEnvironmentIdPackageRouteImport
      parentRoute: typeof EnvironmentsEnvironmentIdRoute
    }
    '/$package/objects/$name': {
      id: '/$package/objects/$name'
      path: '/objects/$name'
      fullPath: '/$package/objects/$name'
      preLoaderRoute: typeof PackageObjectsNameRouteImport
      parentRoute: typeof PackageRoute
    }
    '/environments/$environmentId/$package/': {
      id: '/environments/$environmentId/$package/'
      path: '/'
      fullPath: '/environments/$environmentId/$package/'
      preLoaderRoute: typeof EnvironmentsEnvironmentIdPackageIndexRouteImport
      parentRoute: typeof EnvironmentsEnvironmentIdPackageRoute
    }
    '/$package/metadata/$type/$name': {
      id: '/$package/metadata/$type/$name'
      path: '/metadata/$type/$name'
      fullPath: '/$package/metadata/$type/$name'
      preLoaderRoute: typeof PackageMetadataTypeNameRouteImport
      parentRoute: typeof PackageRoute
    }
    '/environments/$environmentId/$package/objects/$name': {
      id: '/environments/$environmentId/$package/objects/$name'
      path: '/objects/$name'
      fullPath: '/environments/$environmentId/$package/objects/$name'
      preLoaderRoute: typeof EnvironmentsEnvironmentIdPackageObjectsNameRouteImport
      parentRoute: typeof EnvironmentsEnvironmentIdPackageRoute
    }
    '/environments/$environmentId/$package/metadata/$type/$name': {
      id: '/environments/$environmentId/$package/metadata/$type/$name'
      path: '/metadata/$type/$name'
      fullPath: '/environments/$environmentId/$package/metadata/$type/$name'
      preLoaderRoute: typeof EnvironmentsEnvironmentIdPackageMetadataTypeNameRouteImport
      parentRoute: typeof EnvironmentsEnvironmentIdPackageRoute
    }
  }
}

interface PackageRouteChildren {
  PackageIndexRoute: typeof PackageIndexRoute
  PackageObjectsNameRoute: typeof PackageObjectsNameRoute
  PackageMetadataTypeNameRoute: typeof PackageMetadataTypeNameRoute
}

const PackageRouteChildren: PackageRouteChildren = {
  PackageIndexRoute: PackageIndexRoute,
  PackageObjectsNameRoute: PackageObjectsNameRoute,
  PackageMetadataTypeNameRoute: PackageMetadataTypeNameRoute,
}

const PackageRouteWithChildren =
  PackageRoute._addFileChildren(PackageRouteChildren)

interface EnvironmentsEnvironmentIdPackageRouteChildren {
  EnvironmentsEnvironmentIdPackageIndexRoute: typeof EnvironmentsEnvironmentIdPackageIndexRoute
  EnvironmentsEnvironmentIdPackageObjectsNameRoute: typeof EnvironmentsEnvironmentIdPackageObjectsNameRoute
  EnvironmentsEnvironmentIdPackageMetadataTypeNameRoute: typeof EnvironmentsEnvironmentIdPackageMetadataTypeNameRoute
}

const EnvironmentsEnvironmentIdPackageRouteChildren: EnvironmentsEnvironmentIdPackageRouteChildren =
  {
    EnvironmentsEnvironmentIdPackageIndexRoute:
      EnvironmentsEnvironmentIdPackageIndexRoute,
    EnvironmentsEnvironmentIdPackageObjectsNameRoute:
      EnvironmentsEnvironmentIdPackageObjectsNameRoute,
    EnvironmentsEnvironmentIdPackageMetadataTypeNameRoute:
      EnvironmentsEnvironmentIdPackageMetadataTypeNameRoute,
  }

const EnvironmentsEnvironmentIdPackageRouteWithChildren =
  EnvironmentsEnvironmentIdPackageRoute._addFileChildren(
    EnvironmentsEnvironmentIdPackageRouteChildren,
  )

interface EnvironmentsEnvironmentIdRouteChildren {
  EnvironmentsEnvironmentIdPackageRoute: typeof EnvironmentsEnvironmentIdPackageRouteWithChildren
  EnvironmentsEnvironmentIdPackagesRoute: typeof EnvironmentsEnvironmentIdPackagesRoute
  EnvironmentsEnvironmentIdIndexRoute: typeof EnvironmentsEnvironmentIdIndexRoute
}

const EnvironmentsEnvironmentIdRouteChildren: EnvironmentsEnvironmentIdRouteChildren =
  {
    EnvironmentsEnvironmentIdPackageRoute:
      EnvironmentsEnvironmentIdPackageRouteWithChildren,
    EnvironmentsEnvironmentIdPackagesRoute:
      EnvironmentsEnvironmentIdPackagesRoute,
    EnvironmentsEnvironmentIdIndexRoute: EnvironmentsEnvironmentIdIndexRoute,
  }

const EnvironmentsEnvironmentIdRouteWithChildren =
  EnvironmentsEnvironmentIdRoute._addFileChildren(
    EnvironmentsEnvironmentIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PackageRoute: PackageRouteWithChildren,
  ApiConsoleRoute: ApiConsoleRoute,
  LoginRoute: LoginRoute,
  PackagesRoute: PackagesRoute,
  RegisterRoute: RegisterRoute,
  EnvironmentsEnvironmentIdRoute: EnvironmentsEnvironmentIdRouteWithChildren,
  OrgsOrgIdRoute: OrgsOrgIdRoute,
  OrgsNewRoute: OrgsNewRoute,
  EnvironmentsIndexRoute: EnvironmentsIndexRoute,
  OrgsIndexRoute: OrgsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
