/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as ApiConsoleRouteImport } from './routes/api-console'
import { Route as PackageRouteImport } from './routes/$package'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnvironmentsIndexRouteImport } from './routes/environments.index'
import { Route as PackageIndexRouteImport } from './routes/$package.index'
import { Route as EnvironmentsEnvironmentIdRouteImport } from './routes/environments.$environmentId'
import { Route as EnvironmentsEnvironmentIdIndexRouteImport } from './routes/environments.$environmentId.index'
import { Route as PackageObjectsNameRouteImport } from './routes/$package.objects.$name'
import { Route as PackageMetadataTypeNameRouteImport } from './routes/$package.metadata.$type.$name'

const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConsoleRoute = ApiConsoleRouteImport.update({
  id: '/api-console',
  path: '/api-console',
  getParentRoute: () => rootRouteImport,
} as any)
const PackageRoute = PackageRouteImport.update({
  id: '/$package',
  path: '/$package',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvironmentsIndexRoute = EnvironmentsIndexRouteImport.update({
  id: '/environments/',
  path: '/environments/',
  getParentRoute: () => rootRouteImport,
} as any)
const PackageIndexRoute = PackageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PackageRoute,
} as any)
const EnvironmentsEnvironmentIdRoute =
  EnvironmentsEnvironmentIdRouteImport.update({
    id: '/environments/$environmentId',
    path: '/environments/$environmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const EnvironmentsEnvironmentIdIndexRoute =
  EnvironmentsEnvironmentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => EnvironmentsEnvironmentIdRoute,
  } as any)
const PackageObjectsNameRoute = PackageObjectsNameRouteImport.update({
  id: '/objects/$name',
  path: '/objects/$name',
  getParentRoute: () => PackageRoute,
} as any)
const PackageMetadataTypeNameRoute = PackageMetadataTypeNameRouteImport.update({
  id: '/metadata/$type/$name',
  path: '/metadata/$type/$name',
  getParentRoute: () => PackageRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$package': typeof PackageRouteWithChildren
  '/api-console': typeof ApiConsoleRoute
  '/packages': typeof PackagesRoute
  '/environments/$environmentId': typeof EnvironmentsEnvironmentIdRouteWithChildren
  '/$package/': typeof PackageIndexRoute
  '/environments/': typeof EnvironmentsIndexRoute
  '/$package/objects/$name': typeof PackageObjectsNameRoute
  '/environments/$environmentId/': typeof EnvironmentsEnvironmentIdIndexRoute
  '/$package/metadata/$type/$name': typeof PackageMetadataTypeNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-console': typeof ApiConsoleRoute
  '/packages': typeof PackagesRoute
  '/$package': typeof PackageIndexRoute
  '/environments': typeof EnvironmentsIndexRoute
  '/$package/objects/$name': typeof PackageObjectsNameRoute
  '/environments/$environmentId': typeof EnvironmentsEnvironmentIdIndexRoute
  '/$package/metadata/$type/$name': typeof PackageMetadataTypeNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$package': typeof PackageRouteWithChildren
  '/api-console': typeof ApiConsoleRoute
  '/packages': typeof PackagesRoute
  '/environments/$environmentId': typeof EnvironmentsEnvironmentIdRouteWithChildren
  '/$package/': typeof PackageIndexRoute
  '/environments/': typeof EnvironmentsIndexRoute
  '/$package/objects/$name': typeof PackageObjectsNameRoute
  '/environments/$environmentId/': typeof EnvironmentsEnvironmentIdIndexRoute
  '/$package/metadata/$type/$name': typeof PackageMetadataTypeNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$package'
    | '/api-console'
    | '/packages'
    | '/environments/$environmentId'
    | '/$package/'
    | '/environments/'
    | '/$package/objects/$name'
    | '/environments/$environmentId/'
    | '/$package/metadata/$type/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-console'
    | '/packages'
    | '/$package'
    | '/environments'
    | '/$package/objects/$name'
    | '/environments/$environmentId'
    | '/$package/metadata/$type/$name'
  id:
    | '__root__'
    | '/'
    | '/$package'
    | '/api-console'
    | '/packages'
    | '/environments/$environmentId'
    | '/$package/'
    | '/environments/'
    | '/$package/objects/$name'
    | '/environments/$environmentId/'
    | '/$package/metadata/$type/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PackageRoute: typeof PackageRouteWithChildren
  ApiConsoleRoute: typeof ApiConsoleRoute
  PackagesRoute: typeof PackagesRoute
  EnvironmentsEnvironmentIdRoute: typeof EnvironmentsEnvironmentIdRouteWithChildren
  EnvironmentsIndexRoute: typeof EnvironmentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-console': {
      id: '/api-console'
      path: '/api-console'
      fullPath: '/api-console'
      preLoaderRoute: typeof ApiConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$package': {
      id: '/$package'
      path: '/$package'
      fullPath: '/$package'
      preLoaderRoute: typeof PackageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/environments/': {
      id: '/environments/'
      path: '/environments'
      fullPath: '/environments/'
      preLoaderRoute: typeof EnvironmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$package/': {
      id: '/$package/'
      path: '/'
      fullPath: '/$package/'
      preLoaderRoute: typeof PackageIndexRouteImport
      parentRoute: typeof PackageRoute
    }
    '/environments/$environmentId': {
      id: '/environments/$environmentId'
      path: '/environments/$environmentId'
      fullPath: '/environments/$environmentId'
      preLoaderRoute: typeof EnvironmentsEnvironmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/environments/$environmentId/': {
      id: '/environments/$environmentId/'
      path: '/'
      fullPath: '/environments/$environmentId/'
      preLoaderRoute: typeof EnvironmentsEnvironmentIdIndexRouteImport
      parentRoute: typeof EnvironmentsEnvironmentIdRoute
    }
    '/$package/objects/$name': {
      id: '/$package/objects/$name'
      path: '/objects/$name'
      fullPath: '/$package/objects/$name'
      preLoaderRoute: typeof PackageObjectsNameRouteImport
      parentRoute: typeof PackageRoute
    }
    '/$package/metadata/$type/$name': {
      id: '/$package/metadata/$type/$name'
      path: '/metadata/$type/$name'
      fullPath: '/$package/metadata/$type/$name'
      preLoaderRoute: typeof PackageMetadataTypeNameRouteImport
      parentRoute: typeof PackageRoute
    }
  }
}

interface PackageRouteChildren {
  PackageIndexRoute: typeof PackageIndexRoute
  PackageObjectsNameRoute: typeof PackageObjectsNameRoute
  PackageMetadataTypeNameRoute: typeof PackageMetadataTypeNameRoute
}

const PackageRouteChildren: PackageRouteChildren = {
  PackageIndexRoute: PackageIndexRoute,
  PackageObjectsNameRoute: PackageObjectsNameRoute,
  PackageMetadataTypeNameRoute: PackageMetadataTypeNameRoute,
}

const PackageRouteWithChildren =
  PackageRoute._addFileChildren(PackageRouteChildren)

interface EnvironmentsEnvironmentIdRouteChildren {
  EnvironmentsEnvironmentIdIndexRoute: typeof EnvironmentsEnvironmentIdIndexRoute
}

const EnvironmentsEnvironmentIdRouteChildren: EnvironmentsEnvironmentIdRouteChildren =
  {
    EnvironmentsEnvironmentIdIndexRoute: EnvironmentsEnvironmentIdIndexRoute,
  }

const EnvironmentsEnvironmentIdRouteWithChildren =
  EnvironmentsEnvironmentIdRoute._addFileChildren(
    EnvironmentsEnvironmentIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PackageRoute: PackageRouteWithChildren,
  ApiConsoleRoute: ApiConsoleRoute,
  PackagesRoute: PackagesRoute,
  EnvironmentsEnvironmentIdRoute: EnvironmentsEnvironmentIdRouteWithChildren,
  EnvironmentsIndexRoute: EnvironmentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
